/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.routines;


import org.jooq.Parameter;
import org.jooq.Record;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import vc.data.dto.Public;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetUuidData extends AbstractRoutine<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.get_uuid_data.RETURN_VALUE</code>.
     */
    public static final Parameter<Record> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.RECORD, false);

    /**
     * The parameter <code>public.get_uuid_data.p_uuid</code>.
     */
    public static final Parameter<UUID> P_UUID = Internal.createParameter("p_uuid", SQLDataType.UUID, false);

    /**
     * The parameter <code>public.get_uuid_data.time</code>.
     */
    public static final Parameter<OffsetDateTime> TIME = Internal.createParameter("time", SQLDataType.TIMESTAMPWITHTIMEZONE(6), false);

    /**
     * The parameter <code>public.get_uuid_data.data</code>.
     */
    public static final Parameter<String> DATA = Internal.createParameter("data", SQLDataType.CLOB, false);

    /**
     * The parameter <code>public.get_uuid_data.table_name</code>.
     */
    public static final Parameter<String> TABLE_NAME = Internal.createParameter("table_name", SQLDataType.CLOB, false);

    /**
     * Create a new routine call instance
     */
    public GetUuidData() {
        super("get_uuid_data", Public.PUBLIC, DSL.comment(""), SQLDataType.RECORD);

        setReturnParameter(RETURN_VALUE);
        addInParameter(P_UUID);
        addOutParameter(TIME);
        addOutParameter(DATA);
        addOutParameter(TABLE_NAME);
    }

    /**
     * Set the <code>p_uuid</code> parameter IN value to the routine
     */
    public GetUuidData setPUuid(UUID value) {
        setValue(P_UUID, value);
        return this;
    }

    /**
     * Get the <code>time</code> parameter OUT value from the routine
     */
    public OffsetDateTime getTime() {
        return get(TIME);
    }

    /**
     * Get the <code>data</code> parameter OUT value from the routine
     */
    public String getData() {
        return get(DATA);
    }

    /**
     * Get the <code>table_name</code> parameter OUT value from the routine
     */
    public String getTableName() {
        return get(TABLE_NAME);
    }
}
