/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import vc.data.dto.Public;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LastSeen extends AbstractRoutine<OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.last_seen.RETURN_VALUE</code>.
     */
    public static final Parameter<OffsetDateTime> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.TIMESTAMPWITHTIMEZONE(6), false);

    /**
     * The parameter <code>public.last_seen.p_uuid</code>.
     */
    public static final Parameter<UUID> P_UUID = Internal.createParameter("p_uuid", SQLDataType.UUID, false);

    /**
     * The parameter <code>public.last_seen.last_seen</code>.
     */
    public static final Parameter<OffsetDateTime> LAST_SEEN = Internal.createParameter("last_seen", SQLDataType.TIMESTAMPWITHTIMEZONE(6), false);

    /**
     * Create a new routine call instance
     */
    public LastSeen() {
        super("last_seen", Public.PUBLIC, DSL.comment(""), SQLDataType.TIMESTAMPWITHTIMEZONE(6));

        setReturnParameter(RETURN_VALUE);
        addInParameter(P_UUID);
        addOutParameter(LAST_SEEN);
    }

    /**
     * Set the <code>p_uuid</code> parameter IN value to the routine
     */
    public LastSeen setPUuid(UUID value) {
        setValue(P_UUID, value);
        return this;
    }

    /**
     * Get the <code>last_seen</code> parameter OUT value from the routine
     */
    public OffsetDateTime getLastSeen() {
        return get(LAST_SEEN);
    }
}
