/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.routines;


import org.jooq.Parameter;
import org.jooq.Record;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import vc.data.dto.Public;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerStats extends AbstractRoutine<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.player_stats.RETURN_VALUE</code>.
     */
    public static final Parameter<Record> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.RECORD, false);

    /**
     * The parameter <code>public.player_stats.p_uuid</code>.
     */
    public static final Parameter<UUID> P_UUID = Internal.createParameter("p_uuid", SQLDataType.UUID, false);

    /**
     * The parameter <code>public.player_stats.join_count</code>.
     */
    public static final Parameter<Long> JOIN_COUNT = Internal.createParameter("join_count", SQLDataType.BIGINT, false);

    /**
     * The parameter <code>public.player_stats.leave_count</code>.
     */
    public static final Parameter<Long> LEAVE_COUNT = Internal.createParameter("leave_count", SQLDataType.BIGINT, false);

    /**
     * The parameter <code>public.player_stats.death_count</code>.
     */
    public static final Parameter<Long> DEATH_COUNT = Internal.createParameter("death_count", SQLDataType.BIGINT, false);

    /**
     * The parameter <code>public.player_stats.kill_count</code>.
     */
    public static final Parameter<Long> KILL_COUNT = Internal.createParameter("kill_count", SQLDataType.BIGINT, false);

    /**
     * The parameter <code>public.player_stats.first_seen</code>.
     */
    public static final Parameter<OffsetDateTime> FIRST_SEEN = Internal.createParameter("first_seen", SQLDataType.TIMESTAMPWITHTIMEZONE(6), false);

    /**
     * The parameter <code>public.player_stats.last_seen</code>.
     */
    public static final Parameter<OffsetDateTime> LAST_SEEN = Internal.createParameter("last_seen", SQLDataType.TIMESTAMPWITHTIMEZONE(6), false);

    /**
     * The parameter <code>public.player_stats.playtime</code>.
     */
    public static final Parameter<Integer> PLAYTIME = Internal.createParameter("playtime", SQLDataType.INTEGER, false);

    /**
     * The parameter <code>public.player_stats.playtime_30_days</code>.
     */
    public static final Parameter<Integer> PLAYTIME_30_DAYS = Internal.createParameter("playtime_30_days", SQLDataType.INTEGER, false);

    /**
     * The parameter <code>public.player_stats.chats_count</code>.
     */
    public static final Parameter<Long> CHATS_COUNT = Internal.createParameter("chats_count", SQLDataType.BIGINT, false);

    /**
     * The parameter <code>public.player_stats.prio</code>.
     */
    public static final Parameter<Boolean> PRIO = Internal.createParameter("prio", SQLDataType.BOOLEAN, false);

    /**
     * Create a new routine call instance
     */
    public PlayerStats() {
        super("player_stats", Public.PUBLIC, DSL.comment(""), SQLDataType.RECORD);

        setReturnParameter(RETURN_VALUE);
        addInParameter(P_UUID);
        addOutParameter(JOIN_COUNT);
        addOutParameter(LEAVE_COUNT);
        addOutParameter(DEATH_COUNT);
        addOutParameter(KILL_COUNT);
        addOutParameter(FIRST_SEEN);
        addOutParameter(LAST_SEEN);
        addOutParameter(PLAYTIME);
        addOutParameter(PLAYTIME_30_DAYS);
        addOutParameter(CHATS_COUNT);
        addOutParameter(PRIO);
    }

    /**
     * Set the <code>p_uuid</code> parameter IN value to the routine
     */
    public PlayerStats setPUuid(UUID value) {
        setValue(P_UUID, value);
        return this;
    }

    /**
     * Get the <code>join_count</code> parameter OUT value from the routine
     */
    public Long getJoinCount() {
        return get(JOIN_COUNT);
    }

    /**
     * Get the <code>leave_count</code> parameter OUT value from the routine
     */
    public Long getLeaveCount() {
        return get(LEAVE_COUNT);
    }

    /**
     * Get the <code>death_count</code> parameter OUT value from the routine
     */
    public Long getDeathCount() {
        return get(DEATH_COUNT);
    }

    /**
     * Get the <code>kill_count</code> parameter OUT value from the routine
     */
    public Long getKillCount() {
        return get(KILL_COUNT);
    }

    /**
     * Get the <code>first_seen</code> parameter OUT value from the routine
     */
    public OffsetDateTime getFirstSeen() {
        return get(FIRST_SEEN);
    }

    /**
     * Get the <code>last_seen</code> parameter OUT value from the routine
     */
    public OffsetDateTime getLastSeen() {
        return get(LAST_SEEN);
    }

    /**
     * Get the <code>playtime</code> parameter OUT value from the routine
     */
    public Integer getPlaytime() {
        return get(PLAYTIME);
    }

    /**
     * Get the <code>playtime_30_days</code> parameter OUT value from the
     * routine
     */
    public Integer getPlaytime_30Days() {
        return get(PLAYTIME_30_DAYS);
    }

    /**
     * Get the <code>chats_count</code> parameter OUT value from the routine
     */
    public Long getChatsCount() {
        return get(CHATS_COUNT);
    }

    /**
     * Get the <code>prio</code> parameter OUT value from the routine
     */
    public Boolean getPrio() {
        return get(PRIO);
    }
}
