/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.routines;


import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.types.YearToSecond;
import vc.data.dto.Public;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaytimeTimeInterval extends AbstractRoutine<Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.playtime_time_interval.RETURN_VALUE</code>.
     */
    public static final Parameter<Integer> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>public.playtime_time_interval.p_uuid</code>.
     */
    public static final Parameter<UUID> P_UUID = Internal.createParameter("p_uuid", SQLDataType.UUID, false, false);

    /**
     * The parameter <code>public.playtime_time_interval.end_time</code>.
     */
    public static final Parameter<OffsetDateTime> END_TIME = Internal.createParameter("end_time", SQLDataType.TIMESTAMPWITHTIMEZONE(6), false, false);

    /**
     * The parameter <code>public.playtime_time_interval.back_interval</code>.
     */
    public static final Parameter<YearToSecond> BACK_INTERVAL = Internal.createParameter("back_interval", SQLDataType.INTERVAL, false, false);

    /**
     * Create a new routine call instance
     */
    public PlaytimeTimeInterval() {
        super("playtime_time_interval", Public.PUBLIC, SQLDataType.INTEGER);

        setReturnParameter(RETURN_VALUE);
        addInParameter(P_UUID);
        addInParameter(END_TIME);
        addInParameter(BACK_INTERVAL);
    }

    /**
     * Set the <code>p_uuid</code> parameter IN value to the routine
     */
    public void setPUuid(UUID value) {
        setValue(P_UUID, value);
    }

    /**
     * Set the <code>p_uuid</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public PlaytimeTimeInterval setPUuid(Field<UUID> field) {
        setField(P_UUID, field);
        return this;
    }

    /**
     * Set the <code>end_time</code> parameter IN value to the routine
     */
    public void setEndTime(OffsetDateTime value) {
        setValue(END_TIME, value);
    }

    /**
     * Set the <code>end_time</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public PlaytimeTimeInterval setEndTime(Field<OffsetDateTime> field) {
        setField(END_TIME, field);
        return this;
    }

    /**
     * Set the <code>back_interval</code> parameter IN value to the routine
     */
    public void setBackInterval(YearToSecond value) {
        setValue(BACK_INTERVAL, value);
    }

    /**
     * Set the <code>back_interval</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    public PlaytimeTimeInterval setBackInterval(Field<YearToSecond> field) {
        setField(BACK_INTERVAL, field);
        return this;
    }
}
