/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.routines;


import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import vc.data.dto.Public;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Playtime extends AbstractRoutine<Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.playtime.RETURN_VALUE</code>.
     */
    public static final Parameter<Integer> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>public.playtime.p_uuid</code>.
     */
    public static final Parameter<UUID> P_UUID = Internal.createParameter("p_uuid", SQLDataType.UUID, false, false);

    /**
     * Create a new routine call instance
     */
    public Playtime() {
        super("playtime", Public.PUBLIC, SQLDataType.INTEGER);

        setReturnParameter(RETURN_VALUE);
        addInParameter(P_UUID);
    }

    /**
     * Set the <code>p_uuid</code> parameter IN value to the routine
     */
    public void setPUuid(UUID value) {
        setValue(P_UUID, value);
    }

    /**
     * Set the <code>p_uuid</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public Playtime setPUuid(Field<UUID> field) {
        setField(P_UUID, field);
        return this;
    }
}
