/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.routines;


import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import vc.data.dto.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RowEstimator extends AbstractRoutine<Long> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.row_estimator.RETURN_VALUE</code>.
     */
    public static final Parameter<Long> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>public.row_estimator.query</code>.
     */
    public static final Parameter<String> QUERY = Internal.createParameter("query", SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public RowEstimator() {
        super("row_estimator", Public.PUBLIC, SQLDataType.BIGINT);

        setReturnParameter(RETURN_VALUE);
        addInParameter(QUERY);
    }

    /**
     * Set the <code>query</code> parameter IN value to the routine
     */
    public void setQuery(String value) {
        setValue(QUERY, value);
    }

    /**
     * Set the <code>query</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public RowEstimator setQuery(Field<String> field) {
        setField(QUERY, field);
        return this;
    }
}
