server.port=8080
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.login-timeout=60
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.read-only=true
spring.datasource.hikari.data-source-properties.socketTimeout=60
spring.datasource.hikari.data-source-properties.tcpKeepAlive=true
spring.datasource.hikari.data-source-properties.loginTimeout=60
spring.mvc.async.request-timeout=15m
spring.web.error.include-stacktrace=never
resilience4j.ratelimiter.instances.queue.timeoutDuration=5s
resilience4j.ratelimiter.instances.queue.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.queue.limitForPeriod=100
resilience4j.ratelimiter.instances.main.timeoutDuration=10s
resilience4j.ratelimiter.instances.main.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.main.limitForPeriod=2
resilience4j.ratelimiter.instances.cached.timeoutDuration=5s
resilience4j.ratelimiter.instances.cached.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.cached.limitForPeriod=20
resilience4j.bulkhead.instances.chats-ddb.max-concurrent-calls=1
resilience4j.bulkhead.instances.chats-ddb.max-wait-duration=10s
resilience4j.bulkhead.instances.dump.max-concurrent-calls=1
resilience4j.bulkhead.instances.dump.max-wait-duration=10s
management.endpoints.access.default=none
logging.level.web=INFO
logging.file.path=logs/
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=10
logging.pattern.correlation=
scalar.enabled=true
scalar.path=/
scalar.document-download-type=yaml
scalar.dark-mode=true
management.endpoint.scalar.access=none
springdoc.api-docs.enabled=true
springdoc.enable-kotlin=false
spring.devtools.add-properties=false
springdoc.writer-with-order-by-keys=true
cache.ttl.default-ttl=5m
cache.ttl.overrides.queue=1m
cache.ttl.overrides.tablist=1m
cache.ttl.overrides.tablistInfo=1m
cache.ttl.overrides.worldtime=1m
