server.port=8080
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.login-timeout=60
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.read-only=true
spring.datasource.hikari.data-source-properties.socketTimeout=60
spring.datasource.hikari.data-source-properties.tcpKeepAlive=true
spring.datasource.hikari.data-source-properties.loginTimeout=60
spring.mvc.async.request-timeout=15m
server.error.include-stacktrace=never
resilience4j.ratelimiter.instances.queue.timeoutDuration=5000ms
resilience4j.ratelimiter.instances.queue.limitRefreshPeriod=1000ms
resilience4j.ratelimiter.instances.queue.limitForPeriod=100
resilience4j.ratelimiter.instances.main.timeoutDuration=5000ms
resilience4j.ratelimiter.instances.main.limitRefreshPeriod=1000ms
resilience4j.ratelimiter.instances.main.limitForPeriod=2
management.endpoints.access.default=none
logging.level.web=INFO
logging.file.path=logs/
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=10
logging.pattern.correlation=
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.defaultModelExpandDepth=0
springdoc.swagger-ui.defaultModelsExpandDepth=0
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.enable-kotlin=false
spring.devtools.add-properties=false
