/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import vc.data.dto.Public;
import vc.data.dto.tables.records.FirstSeenRecord;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FirstSeen extends TableImpl<FirstSeenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.first_seen</code>
     */
    public static final FirstSeen FIRST_SEEN = new FirstSeen();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FirstSeenRecord> getRecordType() {
        return FirstSeenRecord.class;
    }

    /**
     * The column <code>public.first_seen.first_seen</code>.
     */
    public final TableField<FirstSeenRecord, OffsetDateTime> FIRST_SEEN_ = createField(DSL.name("first_seen"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private FirstSeen(Name alias, Table<FirstSeenRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.UUID)
        });
    }

    private FirstSeen(Name alias, Table<FirstSeenRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private FirstSeen(Name alias, Table<FirstSeenRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>public.first_seen</code> table reference
     */
    public FirstSeen(String alias) {
        this(DSL.name(alias), FIRST_SEEN);
    }

    /**
     * Create an aliased <code>public.first_seen</code> table reference
     */
    public FirstSeen(Name alias) {
        this(alias, FIRST_SEEN);
    }

    /**
     * Create a <code>public.first_seen</code> table reference
     */
    public FirstSeen() {
        this(DSL.name("first_seen"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public FirstSeen as(String alias) {
        return new FirstSeen(DSL.name(alias), this, parameters);
    }

    @Override
    public FirstSeen as(Name alias) {
        return new FirstSeen(alias, this, parameters);
    }

    @Override
    public FirstSeen as(Table<?> alias) {
        return new FirstSeen(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public FirstSeen rename(String name) {
        return new FirstSeen(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public FirstSeen rename(Name name) {
        return new FirstSeen(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public FirstSeen rename(Table<?> name) {
        return new FirstSeen(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public FirstSeen call(
          UUID pUuid
    ) {
        FirstSeen result = new FirstSeen(DSL.name("first_seen"), null, new Field[] {
            DSL.val(pUuid, SQLDataType.UUID)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public FirstSeen call(
          Field<UUID> pUuid
    ) {
        FirstSeen result = new FirstSeen(DSL.name("first_seen"), null, new Field[] {
            pUuid
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
