/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import vc.data.dto.Public;
import vc.data.dto.tables.records.NamesRecord;

import java.time.OffsetDateTime;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Names extends TableImpl<NamesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.names</code>
     */
    public static final Names NAMES = new Names();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NamesRecord> getRecordType() {
        return NamesRecord.class;
    }

    /**
     * The column <code>public.names.name</code>.
     */
    public final TableField<NamesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.names.uuid</code>.
     */
    public final TableField<NamesRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.names.changedtoat</code>.
     */
    public final TableField<NamesRecord, OffsetDateTime> CHANGEDTOAT = createField(DSL.name("changedtoat"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.names.changedfromat</code>.
     */
    public final TableField<NamesRecord, OffsetDateTime> CHANGEDFROMAT = createField(DSL.name("changedfromat"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private Names(Name alias, Table<NamesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Names(Name alias, Table<NamesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.names</code> table reference
     */
    public Names(String alias) {
        this(DSL.name(alias), NAMES);
    }

    /**
     * Create an aliased <code>public.names</code> table reference
     */
    public Names(Name alias) {
        this(alias, NAMES);
    }

    /**
     * Create a <code>public.names</code> table reference
     */
    public Names() {
        this(DSL.name("names"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Names as(String alias) {
        return new Names(DSL.name(alias), this);
    }

    @Override
    public Names as(Name alias) {
        return new Names(alias, this);
    }

    @Override
    public Names as(Table<?> alias) {
        return new Names(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Names rename(String name) {
        return new Names(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Names rename(Name name) {
        return new Names(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Names rename(Table<?> name) {
        return new Names(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Names where(Condition condition) {
        return new Names(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Names where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Names where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Names where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Names where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Names where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Names where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Names where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Names whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Names whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
