/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables;


import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import vc.data.dto.Public;
import vc.data.dto.tables.records.OnlinePlayersRecord;

import java.time.OffsetDateTime;
import java.util.UUID;
import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OnlinePlayers extends TableImpl<OnlinePlayersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.online_players</code>
     */
    public static final OnlinePlayers ONLINE_PLAYERS = new OnlinePlayers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OnlinePlayersRecord> getRecordType() {
        return OnlinePlayersRecord.class;
    }

    /**
     * The column <code>public.online_players.player_name</code>.
     */
    public final TableField<OnlinePlayersRecord, String> PLAYER_NAME = createField(DSL.name("player_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.online_players.player_uuid</code>.
     */
    public final TableField<OnlinePlayersRecord, UUID> PLAYER_UUID = createField(DSL.name("player_uuid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.online_players.join_time</code>.
     */
    public final TableField<OnlinePlayersRecord, OffsetDateTime> JOIN_TIME = createField(DSL.name("join_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private OnlinePlayers(Name alias, Table<OnlinePlayersRecord> aliased) {
        this(alias, aliased, null);
    }

    private OnlinePlayers(Name alias, Table<OnlinePlayersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view());
    }

    /**
     * Create an aliased <code>public.online_players</code> table reference
     */
    public OnlinePlayers(String alias) {
        this(DSL.name(alias), ONLINE_PLAYERS);
    }

    /**
     * Create an aliased <code>public.online_players</code> table reference
     */
    public OnlinePlayers(Name alias) {
        this(alias, ONLINE_PLAYERS);
    }

    /**
     * Create a <code>public.online_players</code> table reference
     */
    public OnlinePlayers() {
        this(DSL.name("online_players"), null);
    }

    public <O extends Record> OnlinePlayers(Table<O> child, ForeignKey<O, OnlinePlayersRecord> key) {
        super(child, key, ONLINE_PLAYERS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public OnlinePlayers as(String alias) {
        return new OnlinePlayers(DSL.name(alias), this);
    }

    @Override
    public OnlinePlayers as(Name alias) {
        return new OnlinePlayers(alias, this);
    }

    @Override
    public OnlinePlayers as(Table<?> alias) {
        return new OnlinePlayers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OnlinePlayers rename(String name) {
        return new OnlinePlayers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OnlinePlayers rename(Name name) {
        return new OnlinePlayers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OnlinePlayers rename(Table<?> name) {
        return new OnlinePlayers(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, UUID, OffsetDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super UUID, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super UUID, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
