/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import vc.data.dto.Public;
import vc.data.dto.tables.records.PlaytimeMonthViewRecord;

import java.math.BigDecimal;
import java.util.Collection;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaytimeMonthView extends TableImpl<PlaytimeMonthViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.playtime_month_view</code>
     */
    public static final PlaytimeMonthView PLAYTIME_MONTH_VIEW = new PlaytimeMonthView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlaytimeMonthViewRecord> getRecordType() {
        return PlaytimeMonthViewRecord.class;
    }

    /**
     * The column <code>public.playtime_month_view.p_uuid</code>.
     */
    public final TableField<PlaytimeMonthViewRecord, UUID> P_UUID = createField(DSL.name("p_uuid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.playtime_month_view.pt_days</code>.
     */
    public final TableField<PlaytimeMonthViewRecord, BigDecimal> PT_DAYS = createField(DSL.name("pt_days"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.playtime_month_view.p_name</code>.
     */
    public final TableField<PlaytimeMonthViewRecord, String> P_NAME = createField(DSL.name("p_name"), SQLDataType.CLOB, this, "");

    private PlaytimeMonthView(Name alias, Table<PlaytimeMonthViewRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PlaytimeMonthView(Name alias, Table<PlaytimeMonthViewRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.materializedView(), where);
    }

    /**
     * Create an aliased <code>public.playtime_month_view</code> table reference
     */
    public PlaytimeMonthView(String alias) {
        this(DSL.name(alias), PLAYTIME_MONTH_VIEW);
    }

    /**
     * Create an aliased <code>public.playtime_month_view</code> table reference
     */
    public PlaytimeMonthView(Name alias) {
        this(alias, PLAYTIME_MONTH_VIEW);
    }

    /**
     * Create a <code>public.playtime_month_view</code> table reference
     */
    public PlaytimeMonthView() {
        this(DSL.name("playtime_month_view"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public PlaytimeMonthView as(String alias) {
        return new PlaytimeMonthView(DSL.name(alias), this);
    }

    @Override
    public PlaytimeMonthView as(Name alias) {
        return new PlaytimeMonthView(alias, this);
    }

    @Override
    public PlaytimeMonthView as(Table<?> alias) {
        return new PlaytimeMonthView(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaytimeMonthView rename(String name) {
        return new PlaytimeMonthView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaytimeMonthView rename(Name name) {
        return new PlaytimeMonthView(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaytimeMonthView rename(Table<?> name) {
        return new PlaytimeMonthView(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaytimeMonthView where(Condition condition) {
        return new PlaytimeMonthView(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaytimeMonthView where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaytimeMonthView where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaytimeMonthView where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaytimeMonthView where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaytimeMonthView where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaytimeMonthView where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaytimeMonthView where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaytimeMonthView whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaytimeMonthView whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
