/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import vc.data.dto.Public;
import vc.data.dto.tables.records.PlaytimeAllRecord;

import java.util.UUID;
import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaytimeAll extends TableImpl<PlaytimeAllRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.playtime_all</code>
     */
    public static final PlaytimeAll PLAYTIME_ALL = new PlaytimeAll();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlaytimeAllRecord> getRecordType() {
        return PlaytimeAllRecord.class;
    }

    /**
     * The column <code>public.playtime_all.p_uuid</code>.
     */
    public final TableField<PlaytimeAllRecord, UUID> P_UUID = createField(DSL.name("p_uuid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.playtime_all.playtime</code>.
     */
    public final TableField<PlaytimeAllRecord, Integer> PLAYTIME = createField(DSL.name("playtime"), SQLDataType.INTEGER, this, "");

    private PlaytimeAll(Name alias, Table<PlaytimeAllRecord> aliased) {
        this(alias, aliased, new Field[] {
        });
    }

    private PlaytimeAll(Name alias, Table<PlaytimeAllRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function());
    }

    /**
     * Create an aliased <code>public.playtime_all</code> table reference
     */
    public PlaytimeAll(String alias) {
        this(DSL.name(alias), PLAYTIME_ALL);
    }

    /**
     * Create an aliased <code>public.playtime_all</code> table reference
     */
    public PlaytimeAll(Name alias) {
        this(alias, PLAYTIME_ALL);
    }

    /**
     * Create a <code>public.playtime_all</code> table reference
     */
    public PlaytimeAll() {
        this(DSL.name("playtime_all"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public PlaytimeAll as(String alias) {
        return new PlaytimeAll(DSL.name(alias), this, parameters);
    }

    @Override
    public PlaytimeAll as(Name alias) {
        return new PlaytimeAll(alias, this, parameters);
    }

    @Override
    public PlaytimeAll as(Table<?> alias) {
        return new PlaytimeAll(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaytimeAll rename(String name) {
        return new PlaytimeAll(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaytimeAll rename(Name name) {
        return new PlaytimeAll(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaytimeAll rename(Table<?> name) {
        return new PlaytimeAll(name.getQualifiedName(), null, parameters);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Call this table-valued function
     */
    public PlaytimeAll call() {
        PlaytimeAll result = new PlaytimeAll(DSL.name("playtime_all"), null, new Field[] {});

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super UUID, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super UUID, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
