/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import vc.data.dto.Public;
import vc.data.dto.tables.records.PlaytimeRecord;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Playtime extends TableImpl<PlaytimeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.playtime</code>
     */
    public static final Playtime PLAYTIME = new Playtime();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlaytimeRecord> getRecordType() {
        return PlaytimeRecord.class;
    }

    /**
     * The column <code>public.playtime.id</code>.
     */
    public final TableField<PlaytimeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedAlwaysAsIdentity(), this, "");

    /**
     * The column <code>public.playtime.player_uuid</code>.
     */
    public final TableField<PlaytimeRecord, UUID> PLAYER_UUID = createField(DSL.name("player_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.playtime.player_name</code>.
     */
    public final TableField<PlaytimeRecord, String> PLAYER_NAME = createField(DSL.name("player_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.playtime.playtime_seconds</code>.
     */
    public final TableField<PlaytimeRecord, Integer> PLAYTIME_SECONDS = createField(DSL.name("playtime_seconds"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.playtime.start_time</code>.
     */
    public final TableField<PlaytimeRecord, OffsetDateTime> START_TIME = createField(DSL.name("start_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.playtime.end_time</code>.
     */
    public final TableField<PlaytimeRecord, OffsetDateTime> END_TIME = createField(DSL.name("end_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private Playtime(Name alias, Table<PlaytimeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Playtime(Name alias, Table<PlaytimeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.playtime</code> table reference
     */
    public Playtime(String alias) {
        this(DSL.name(alias), PLAYTIME);
    }

    /**
     * Create an aliased <code>public.playtime</code> table reference
     */
    public Playtime(Name alias) {
        this(alias, PLAYTIME);
    }

    /**
     * Create a <code>public.playtime</code> table reference
     */
    public Playtime() {
        this(DSL.name("playtime"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PlaytimeRecord, Long> getIdentity() {
        return (Identity<PlaytimeRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PlaytimeRecord> getPrimaryKey() {
        return Internal.createUniqueKey(Playtime.PLAYTIME, DSL.name("playtime_pk"), new TableField[] { Playtime.PLAYTIME.ID }, true);
    }

    @Override
    public Playtime as(String alias) {
        return new Playtime(DSL.name(alias), this);
    }

    @Override
    public Playtime as(Name alias) {
        return new Playtime(alias, this);
    }

    @Override
    public Playtime as(Table<?> alias) {
        return new Playtime(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Playtime rename(String name) {
        return new Playtime(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Playtime rename(Name name) {
        return new Playtime(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Playtime rename(Table<?> name) {
        return new Playtime(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Playtime where(Condition condition) {
        return new Playtime(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Playtime where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Playtime where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Playtime where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Playtime where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Playtime where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Playtime where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Playtime where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Playtime whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Playtime whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
