/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import vc.data.dto.Public;
import vc.data.dto.tables.records.PriorityPlayersViewRecord;

import java.util.Collection;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PriorityPlayersView extends TableImpl<PriorityPlayersViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.priority_players_view</code>
     */
    public static final PriorityPlayersView PRIORITY_PLAYERS_VIEW = new PriorityPlayersView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PriorityPlayersViewRecord> getRecordType() {
        return PriorityPlayersViewRecord.class;
    }

    /**
     * The column <code>public.priority_players_view.player_name</code>.
     */
    public final TableField<PriorityPlayersViewRecord, String> PLAYER_NAME = createField(DSL.name("player_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.priority_players_view.player_uuid</code>.
     */
    public final TableField<PriorityPlayersViewRecord, UUID> PLAYER_UUID = createField(DSL.name("player_uuid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.priority_players_view.priority_joins</code>.
     */
    public final TableField<PriorityPlayersViewRecord, Long> PRIORITY_JOINS = createField(DSL.name("priority_joins"), SQLDataType.BIGINT, this, "");

    /**
     * The column
     * <code>public.priority_players_view.priority_session_length_count</code>.
     */
    public final TableField<PriorityPlayersViewRecord, Long> PRIORITY_SESSION_LENGTH_COUNT = createField(DSL.name("priority_session_length_count"), SQLDataType.BIGINT, this, "");

    private PriorityPlayersView(Name alias, Table<PriorityPlayersViewRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PriorityPlayersView(Name alias, Table<PriorityPlayersViewRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.materializedView(), where);
    }

    /**
     * Create an aliased <code>public.priority_players_view</code> table
     * reference
     */
    public PriorityPlayersView(String alias) {
        this(DSL.name(alias), PRIORITY_PLAYERS_VIEW);
    }

    /**
     * Create an aliased <code>public.priority_players_view</code> table
     * reference
     */
    public PriorityPlayersView(Name alias) {
        this(alias, PRIORITY_PLAYERS_VIEW);
    }

    /**
     * Create a <code>public.priority_players_view</code> table reference
     */
    public PriorityPlayersView() {
        this(DSL.name("priority_players_view"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public PriorityPlayersView as(String alias) {
        return new PriorityPlayersView(DSL.name(alias), this);
    }

    @Override
    public PriorityPlayersView as(Name alias) {
        return new PriorityPlayersView(alias, this);
    }

    @Override
    public PriorityPlayersView as(Table<?> alias) {
        return new PriorityPlayersView(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PriorityPlayersView rename(String name) {
        return new PriorityPlayersView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PriorityPlayersView rename(Name name) {
        return new PriorityPlayersView(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PriorityPlayersView rename(Table<?> name) {
        return new PriorityPlayersView(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriorityPlayersView where(Condition condition) {
        return new PriorityPlayersView(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriorityPlayersView where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriorityPlayersView where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriorityPlayersView where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PriorityPlayersView where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PriorityPlayersView where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PriorityPlayersView where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PriorityPlayersView where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriorityPlayersView whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriorityPlayersView whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
