/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import vc.data.dto.Public;
import vc.data.dto.tables.records.PriorityPlayersRecord;

import java.util.Collection;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PriorityPlayers extends TableImpl<PriorityPlayersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.priority_players</code>
     */
    public static final PriorityPlayers PRIORITY_PLAYERS = new PriorityPlayers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PriorityPlayersRecord> getRecordType() {
        return PriorityPlayersRecord.class;
    }

    /**
     * The column <code>public.priority_players.player_uuid</code>.
     */
    public final TableField<PriorityPlayersRecord, UUID> PLAYER_UUID = createField(DSL.name("player_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.priority_players.player_name</code>.
     */
    public final TableField<PriorityPlayersRecord, String> PLAYER_NAME = createField(DSL.name("player_name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.priority_players.priority_joins</code>.
     */
    public final TableField<PriorityPlayersRecord, Long> PRIORITY_JOINS = createField(DSL.name("priority_joins"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>public.priority_players.priority_session_length_count</code>.
     */
    public final TableField<PriorityPlayersRecord, Long> PRIORITY_SESSION_LENGTH_COUNT = createField(DSL.name("priority_session_length_count"), SQLDataType.BIGINT.nullable(false), this, "");

    private PriorityPlayers(Name alias, Table<PriorityPlayersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PriorityPlayers(Name alias, Table<PriorityPlayersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.priority_players</code> table reference
     */
    public PriorityPlayers(String alias) {
        this(DSL.name(alias), PRIORITY_PLAYERS);
    }

    /**
     * Create an aliased <code>public.priority_players</code> table reference
     */
    public PriorityPlayers(Name alias) {
        this(alias, PRIORITY_PLAYERS);
    }

    /**
     * Create a <code>public.priority_players</code> table reference
     */
    public PriorityPlayers() {
        this(DSL.name("priority_players"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public PriorityPlayers as(String alias) {
        return new PriorityPlayers(DSL.name(alias), this);
    }

    @Override
    public PriorityPlayers as(Name alias) {
        return new PriorityPlayers(alias, this);
    }

    @Override
    public PriorityPlayers as(Table<?> alias) {
        return new PriorityPlayers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PriorityPlayers rename(String name) {
        return new PriorityPlayers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PriorityPlayers rename(Name name) {
        return new PriorityPlayers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PriorityPlayers rename(Table<?> name) {
        return new PriorityPlayers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriorityPlayers where(Condition condition) {
        return new PriorityPlayers(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriorityPlayers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriorityPlayers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriorityPlayers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PriorityPlayers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PriorityPlayers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PriorityPlayers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PriorityPlayers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriorityPlayers whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PriorityPlayers whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
