/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import vc.data.dto.Public;
import vc.data.dto.tables.records.RestartsRecord;

import java.time.OffsetDateTime;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Restarts extends TableImpl<RestartsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.restarts</code>
     */
    public static final Restarts RESTARTS = new Restarts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RestartsRecord> getRecordType() {
        return RestartsRecord.class;
    }

    /**
     * The column <code>public.restarts.time</code>.
     */
    public final TableField<RestartsRecord, OffsetDateTime> TIME = createField(DSL.name("time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.restarts.id</code>.
     */
    public final TableField<RestartsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Restarts(Name alias, Table<RestartsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Restarts(Name alias, Table<RestartsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.restarts</code> table reference
     */
    public Restarts(String alias) {
        this(DSL.name(alias), RESTARTS);
    }

    /**
     * Create an aliased <code>public.restarts</code> table reference
     */
    public Restarts(Name alias) {
        this(alias, RESTARTS);
    }

    /**
     * Create a <code>public.restarts</code> table reference
     */
    public Restarts() {
        this(DSL.name("restarts"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<RestartsRecord> getPrimaryKey() {
        return Internal.createUniqueKey(Restarts.RESTARTS, DSL.name("restarts_pkey"), new TableField[] { Restarts.RESTARTS.ID }, true);
    }

    @Override
    public Restarts as(String alias) {
        return new Restarts(DSL.name(alias), this);
    }

    @Override
    public Restarts as(Name alias) {
        return new Restarts(alias, this);
    }

    @Override
    public Restarts as(Table<?> alias) {
        return new Restarts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Restarts rename(String name) {
        return new Restarts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Restarts rename(Name name) {
        return new Restarts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Restarts rename(Table<?> name) {
        return new Restarts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Restarts where(Condition condition) {
        return new Restarts(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Restarts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Restarts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Restarts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Restarts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Restarts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Restarts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Restarts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Restarts whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Restarts whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
