/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import vc.data.dto.Public;
import vc.data.dto.tables.records.TablistTextRecord;

import java.time.OffsetDateTime;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TablistText extends TableImpl<TablistTextRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tablist_text</code>
     */
    public static final TablistText TABLIST_TEXT = new TablistText();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TablistTextRecord> getRecordType() {
        return TablistTextRecord.class;
    }

    /**
     * The column <code>public.tablist_text.id</code>.
     */
    public final TableField<TablistTextRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedAlwaysAsIdentity(), this, "");

    /**
     * The column <code>public.tablist_text.time</code>.
     */
    public final TableField<TablistTextRecord, OffsetDateTime> TIME = createField(DSL.name("time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.tablist_text.header_text</code>.
     */
    public final TableField<TablistTextRecord, String> HEADER_TEXT = createField(DSL.name("header_text"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.tablist_text.header_json</code>.
     */
    public final TableField<TablistTextRecord, String> HEADER_JSON = createField(DSL.name("header_json"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.tablist_text.footer_text</code>.
     */
    public final TableField<TablistTextRecord, String> FOOTER_TEXT = createField(DSL.name("footer_text"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.tablist_text.footer_json</code>.
     */
    public final TableField<TablistTextRecord, String> FOOTER_JSON = createField(DSL.name("footer_json"), SQLDataType.CLOB, this, "");

    private TablistText(Name alias, Table<TablistTextRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TablistText(Name alias, Table<TablistTextRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.tablist_text</code> table reference
     */
    public TablistText(String alias) {
        this(DSL.name(alias), TABLIST_TEXT);
    }

    /**
     * Create an aliased <code>public.tablist_text</code> table reference
     */
    public TablistText(Name alias) {
        this(alias, TABLIST_TEXT);
    }

    /**
     * Create a <code>public.tablist_text</code> table reference
     */
    public TablistText() {
        this(DSL.name("tablist_text"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TablistTextRecord, Long> getIdentity() {
        return (Identity<TablistTextRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TablistTextRecord> getPrimaryKey() {
        return Internal.createUniqueKey(TablistText.TABLIST_TEXT, DSL.name("tablist_text_pk"), new TableField[] { TablistText.TABLIST_TEXT.ID }, true);
    }

    @Override
    public TablistText as(String alias) {
        return new TablistText(DSL.name(alias), this);
    }

    @Override
    public TablistText as(Name alias) {
        return new TablistText(alias, this);
    }

    @Override
    public TablistText as(Table<?> alias) {
        return new TablistText(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TablistText rename(String name) {
        return new TablistText(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TablistText rename(Name name) {
        return new TablistText(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TablistText rename(Table<?> name) {
        return new TablistText(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TablistText where(Condition condition) {
        return new TablistText(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TablistText where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TablistText where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TablistText where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TablistText where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TablistText where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TablistText where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TablistText where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TablistText whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TablistText whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
