/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import vc.data.dto.Public;
import vc.data.dto.tables.records.TablistInfoRecord;

import java.util.Collection;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TablistInfo extends TableImpl<TablistInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tablist_info</code>
     */
    public static final TablistInfo TABLIST_INFO = new TablistInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TablistInfoRecord> getRecordType() {
        return TablistInfoRecord.class;
    }

    /**
     * The column <code>public.tablist_info.player_name</code>.
     */
    public final TableField<TablistInfoRecord, String> PLAYER_NAME = createField(DSL.name("player_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.tablist_info.player_uuid</code>.
     */
    public final TableField<TablistInfoRecord, UUID> PLAYER_UUID = createField(DSL.name("player_uuid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.tablist_info.prio</code>.
     */
    public final TableField<TablistInfoRecord, Boolean> PRIO = createField(DSL.name("prio"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.tablist_info.is_bot</code>.
     */
    public final TableField<TablistInfoRecord, Boolean> IS_BOT = createField(DSL.name("is_bot"), SQLDataType.BOOLEAN, this, "");

    private TablistInfo(Name alias, Table<TablistInfoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TablistInfo(Name alias, Table<TablistInfoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        CREATE VIEW "tablist_info" AS  SELECT t.player_name,
         t.player_uuid,
             CASE
                 WHEN (pv.player_uuid IS NOT NULL) THEN true
                 ELSE false
             END AS prio,
             CASE
                 WHEN (mb.p_uuid IS NOT NULL) THEN true
                 ELSE false
             END AS is_bot
        FROM ((tablist t
          LEFT JOIN priority_players_view pv ON ((t.player_uuid = pv.player_uuid)))
          LEFT JOIN max_cons_month_view mb ON ((t.player_uuid = mb.p_uuid)));
        """), where);
    }

    /**
     * Create an aliased <code>public.tablist_info</code> table reference
     */
    public TablistInfo(String alias) {
        this(DSL.name(alias), TABLIST_INFO);
    }

    /**
     * Create an aliased <code>public.tablist_info</code> table reference
     */
    public TablistInfo(Name alias) {
        this(alias, TABLIST_INFO);
    }

    /**
     * Create a <code>public.tablist_info</code> table reference
     */
    public TablistInfo() {
        this(DSL.name("tablist_info"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public TablistInfo as(String alias) {
        return new TablistInfo(DSL.name(alias), this);
    }

    @Override
    public TablistInfo as(Name alias) {
        return new TablistInfo(alias, this);
    }

    @Override
    public TablistInfo as(Table<?> alias) {
        return new TablistInfo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TablistInfo rename(String name) {
        return new TablistInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TablistInfo rename(Name name) {
        return new TablistInfo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TablistInfo rename(Table<?> name) {
        return new TablistInfo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TablistInfo where(Condition condition) {
        return new TablistInfo(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TablistInfo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TablistInfo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TablistInfo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TablistInfo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TablistInfo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TablistInfo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TablistInfo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TablistInfo whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TablistInfo whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
