/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import vc.data.dto.Public;
import vc.data.dto.tables.records.TopPlaytimeAllTimeViewRecord;

import java.util.Collection;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TopPlaytimeAllTimeView extends TableImpl<TopPlaytimeAllTimeViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.top_playtime_all_time_view</code>
     */
    public static final TopPlaytimeAllTimeView TOP_PLAYTIME_ALL_TIME_VIEW = new TopPlaytimeAllTimeView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TopPlaytimeAllTimeViewRecord> getRecordType() {
        return TopPlaytimeAllTimeViewRecord.class;
    }

    /**
     * The column <code>public.top_playtime_all_time_view.player_uuid</code>.
     */
    public final TableField<TopPlaytimeAllTimeViewRecord, UUID> PLAYER_UUID = createField(DSL.name("player_uuid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.top_playtime_all_time_view.player_name</code>.
     */
    public final TableField<TopPlaytimeAllTimeViewRecord, String> PLAYER_NAME = createField(DSL.name("player_name"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public.top_playtime_all_time_view.playtime_seconds</code>.
     */
    public final TableField<TopPlaytimeAllTimeViewRecord, Long> PLAYTIME_SECONDS = createField(DSL.name("playtime_seconds"), SQLDataType.BIGINT, this, "");

    private TopPlaytimeAllTimeView(Name alias, Table<TopPlaytimeAllTimeViewRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TopPlaytimeAllTimeView(Name alias, Table<TopPlaytimeAllTimeViewRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.materializedView(), where);
    }

    /**
     * Create an aliased <code>public.top_playtime_all_time_view</code> table
     * reference
     */
    public TopPlaytimeAllTimeView(String alias) {
        this(DSL.name(alias), TOP_PLAYTIME_ALL_TIME_VIEW);
    }

    /**
     * Create an aliased <code>public.top_playtime_all_time_view</code> table
     * reference
     */
    public TopPlaytimeAllTimeView(Name alias) {
        this(alias, TOP_PLAYTIME_ALL_TIME_VIEW);
    }

    /**
     * Create a <code>public.top_playtime_all_time_view</code> table reference
     */
    public TopPlaytimeAllTimeView() {
        this(DSL.name("top_playtime_all_time_view"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public TopPlaytimeAllTimeView as(String alias) {
        return new TopPlaytimeAllTimeView(DSL.name(alias), this);
    }

    @Override
    public TopPlaytimeAllTimeView as(Name alias) {
        return new TopPlaytimeAllTimeView(alias, this);
    }

    @Override
    public TopPlaytimeAllTimeView as(Table<?> alias) {
        return new TopPlaytimeAllTimeView(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TopPlaytimeAllTimeView rename(String name) {
        return new TopPlaytimeAllTimeView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TopPlaytimeAllTimeView rename(Name name) {
        return new TopPlaytimeAllTimeView(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TopPlaytimeAllTimeView rename(Table<?> name) {
        return new TopPlaytimeAllTimeView(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TopPlaytimeAllTimeView where(Condition condition) {
        return new TopPlaytimeAllTimeView(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TopPlaytimeAllTimeView where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TopPlaytimeAllTimeView where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TopPlaytimeAllTimeView where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TopPlaytimeAllTimeView where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TopPlaytimeAllTimeView where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TopPlaytimeAllTimeView where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TopPlaytimeAllTimeView where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TopPlaytimeAllTimeView whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TopPlaytimeAllTimeView whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
