/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import vc.data.dto.Public;
import vc.data.dto.tables.records.TopPlaytimeMonthViewRecord;

import java.util.Collection;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TopPlaytimeMonthView extends TableImpl<TopPlaytimeMonthViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.top_playtime_month_view</code>
     */
    public static final TopPlaytimeMonthView TOP_PLAYTIME_MONTH_VIEW = new TopPlaytimeMonthView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TopPlaytimeMonthViewRecord> getRecordType() {
        return TopPlaytimeMonthViewRecord.class;
    }

    /**
     * The column <code>public.top_playtime_month_view.player_uuid</code>.
     */
    public final TableField<TopPlaytimeMonthViewRecord, UUID> PLAYER_UUID = createField(DSL.name("player_uuid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.top_playtime_month_view.player_name</code>.
     */
    public final TableField<TopPlaytimeMonthViewRecord, String> PLAYER_NAME = createField(DSL.name("player_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.top_playtime_month_view.playtime_seconds</code>.
     */
    public final TableField<TopPlaytimeMonthViewRecord, Long> PLAYTIME_SECONDS = createField(DSL.name("playtime_seconds"), SQLDataType.BIGINT, this, "");

    private TopPlaytimeMonthView(Name alias, Table<TopPlaytimeMonthViewRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TopPlaytimeMonthView(Name alias, Table<TopPlaytimeMonthViewRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "top_playtime_month_view" as  WITH playtime_summary AS (
                SELECT playtime.player_uuid,
                   sum(playtime.playtime_seconds) AS total_playtime
                  FROM playtime
                 WHERE ((playtime.start_time >= (now() - '30 days'::interval)) AND (playtime.end_time <= now()))
                 GROUP BY playtime.player_uuid
               ), latest_names AS (
                SELECT playtime.player_uuid,
                   playtime.player_name,
                   row_number() OVER (PARTITION BY playtime.player_uuid ORDER BY playtime.end_time DESC) AS rn
                  FROM playtime
                 WHERE ((playtime.start_time >= (now() - '30 days'::interval)) AND (playtime.end_time <= now()))
               )
        SELECT ps.player_uuid,
           ln.player_name,
           ps.total_playtime AS playtime_seconds
          FROM (playtime_summary ps
            JOIN latest_names ln ON (((ps.player_uuid = ln.player_uuid) AND (ln.rn = 1))))
         ORDER BY ps.total_playtime DESC
        LIMIT 1000;
        """), where);
    }

    /**
     * Create an aliased <code>public.top_playtime_month_view</code> table
     * reference
     */
    public TopPlaytimeMonthView(String alias) {
        this(DSL.name(alias), TOP_PLAYTIME_MONTH_VIEW);
    }

    /**
     * Create an aliased <code>public.top_playtime_month_view</code> table
     * reference
     */
    public TopPlaytimeMonthView(Name alias) {
        this(alias, TOP_PLAYTIME_MONTH_VIEW);
    }

    /**
     * Create a <code>public.top_playtime_month_view</code> table reference
     */
    public TopPlaytimeMonthView() {
        this(DSL.name("top_playtime_month_view"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public TopPlaytimeMonthView as(String alias) {
        return new TopPlaytimeMonthView(DSL.name(alias), this);
    }

    @Override
    public TopPlaytimeMonthView as(Name alias) {
        return new TopPlaytimeMonthView(alias, this);
    }

    @Override
    public TopPlaytimeMonthView as(Table<?> alias) {
        return new TopPlaytimeMonthView(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TopPlaytimeMonthView rename(String name) {
        return new TopPlaytimeMonthView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TopPlaytimeMonthView rename(Name name) {
        return new TopPlaytimeMonthView(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TopPlaytimeMonthView rename(Table<?> name) {
        return new TopPlaytimeMonthView(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TopPlaytimeMonthView where(Condition condition) {
        return new TopPlaytimeMonthView(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TopPlaytimeMonthView where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TopPlaytimeMonthView where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TopPlaytimeMonthView where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TopPlaytimeMonthView where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TopPlaytimeMonthView where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TopPlaytimeMonthView where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TopPlaytimeMonthView where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TopPlaytimeMonthView whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TopPlaytimeMonthView whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
