/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import vc.data.dto.Public;
import vc.data.dto.tables.records.WorldtimeRecord;

import java.time.OffsetDateTime;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Worldtime extends TableImpl<WorldtimeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.worldtime</code>
     */
    public static final Worldtime WORLDTIME = new Worldtime();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorldtimeRecord> getRecordType() {
        return WorldtimeRecord.class;
    }

    /**
     * The column <code>public.worldtime.time</code>.
     */
    public final TableField<WorldtimeRecord, OffsetDateTime> TIME = createField(DSL.name("time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.worldtime.worldage</code>.
     */
    public final TableField<WorldtimeRecord, Long> WORLDAGE = createField(DSL.name("worldage"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.worldtime.worldtime</code>.
     */
    public final TableField<WorldtimeRecord, Long> WORLDTIME_ = createField(DSL.name("worldtime"), SQLDataType.BIGINT.nullable(false), this, "");

    private Worldtime(Name alias, Table<WorldtimeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Worldtime(Name alias, Table<WorldtimeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.worldtime</code> table reference
     */
    public Worldtime(String alias) {
        this(DSL.name(alias), WORLDTIME);
    }

    /**
     * Create an aliased <code>public.worldtime</code> table reference
     */
    public Worldtime(Name alias) {
        this(alias, WORLDTIME);
    }

    /**
     * Create a <code>public.worldtime</code> table reference
     */
    public Worldtime() {
        this(DSL.name("worldtime"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Worldtime as(String alias) {
        return new Worldtime(DSL.name(alias), this);
    }

    @Override
    public Worldtime as(Name alias) {
        return new Worldtime(alias, this);
    }

    @Override
    public Worldtime as(Table<?> alias) {
        return new Worldtime(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Worldtime rename(String name) {
        return new Worldtime(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Worldtime rename(Name name) {
        return new Worldtime(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Worldtime rename(Table<?> name) {
        return new Worldtime(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Worldtime where(Condition condition) {
        return new Worldtime(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Worldtime where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Worldtime where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Worldtime where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Worldtime where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Worldtime where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Worldtime where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Worldtime where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Worldtime whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Worldtime whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
