/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.FirstSeen;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FirstSeenRecord extends TableRecordImpl<FirstSeenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.first_seen.first_seen</code>.
     */
    public FirstSeenRecord setFirstSeen(OffsetDateTime value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.first_seen.first_seen</code>.
     */
    public OffsetDateTime getFirstSeen() {
        return (OffsetDateTime) get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FirstSeenRecord
     */
    public FirstSeenRecord() {
        super(FirstSeen.FIRST_SEEN);
    }

    /**
     * Create a detached, initialised FirstSeenRecord
     */
    public FirstSeenRecord(OffsetDateTime firstSeen) {
        super(FirstSeen.FIRST_SEEN);

        setFirstSeen(firstSeen);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised FirstSeenRecord
     */
    public FirstSeenRecord(vc.data.dto.tables.pojos.FirstSeen value) {
        super(FirstSeen.FIRST_SEEN);

        if (value != null) {
            setFirstSeen(value.getFirstSeen());
            resetTouchedOnNotNull();
        }
    }
}
