/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.GetUuidData;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetUuidDataRecord extends TableRecordImpl<GetUuidDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.get_uuid_data.time</code>.
     */
    public GetUuidDataRecord setTime(OffsetDateTime value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.get_uuid_data.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(0);
    }

    /**
     * Setter for <code>public.get_uuid_data.data</code>.
     */
    public GetUuidDataRecord setData(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.get_uuid_data.data</code>.
     */
    public String getData() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.get_uuid_data.table_name</code>.
     */
    public GetUuidDataRecord setTableName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.get_uuid_data.table_name</code>.
     */
    public String getTableName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetUuidDataRecord
     */
    public GetUuidDataRecord() {
        super(GetUuidData.GET_UUID_DATA);
    }

    /**
     * Create a detached, initialised GetUuidDataRecord
     */
    public GetUuidDataRecord(OffsetDateTime time, String data, String tableName) {
        super(GetUuidData.GET_UUID_DATA);

        setTime(time);
        setData(data);
        setTableName(tableName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised GetUuidDataRecord
     */
    public GetUuidDataRecord(vc.data.dto.tables.pojos.GetUuidData value) {
        super(GetUuidData.GET_UUID_DATA);

        if (value != null) {
            setTime(value.getTime());
            setData(value.getData());
            setTableName(value.getTableName());
            resetChangedOnNotNull();
        }
    }
}
