/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.MaxConsMonthView;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MaxConsMonthViewRecord extends TableRecordImpl<MaxConsMonthViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.max_cons_month_view.p_uuid</code>.
     */
    public MaxConsMonthViewRecord setPUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.max_cons_month_view.p_uuid</code>.
     */
    public UUID getPUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.max_cons_month_view.max_cons</code>.
     */
    public MaxConsMonthViewRecord setMaxCons(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.max_cons_month_view.max_cons</code>.
     */
    public Integer getMaxCons() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.max_cons_month_view.p_name</code>.
     */
    public MaxConsMonthViewRecord setPName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.max_cons_month_view.p_name</code>.
     */
    public String getPName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MaxConsMonthViewRecord
     */
    public MaxConsMonthViewRecord() {
        super(MaxConsMonthView.MAX_CONS_MONTH_VIEW);
    }

    /**
     * Create a detached, initialised MaxConsMonthViewRecord
     */
    public MaxConsMonthViewRecord(UUID pUuid, Integer maxCons, String pName) {
        super(MaxConsMonthView.MAX_CONS_MONTH_VIEW);

        setPUuid(pUuid);
        setMaxCons(maxCons);
        setPName(pName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MaxConsMonthViewRecord
     */
    public MaxConsMonthViewRecord(vc.data.dto.tables.pojos.MaxConsMonthView value) {
        super(MaxConsMonthView.MAX_CONS_MONTH_VIEW);

        if (value != null) {
            setPUuid(value.getPUuid());
            setMaxCons(value.getMaxCons());
            setPName(value.getPName());
            resetChangedOnNotNull();
        }
    }
}
