/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;

import vc.data.dto.tables.MaxConsMonthView;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MaxConsMonthViewRecord extends TableRecordImpl<MaxConsMonthViewRecord> implements Record3<UUID, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.max_cons_month_view.p_uuid</code>.
     */
    public MaxConsMonthViewRecord setPUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.max_cons_month_view.p_uuid</code>.
     */
    public UUID getPUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.max_cons_month_view.max_cons</code>.
     */
    public MaxConsMonthViewRecord setMaxCons(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.max_cons_month_view.max_cons</code>.
     */
    public Integer getMaxCons() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.max_cons_month_view.p_name</code>.
     */
    public MaxConsMonthViewRecord setPName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.max_cons_month_view.p_name</code>.
     */
    public String getPName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return MaxConsMonthView.MAX_CONS_MONTH_VIEW.P_UUID;
    }

    @Override
    public Field<Integer> field2() {
        return MaxConsMonthView.MAX_CONS_MONTH_VIEW.MAX_CONS;
    }

    @Override
    public Field<String> field3() {
        return MaxConsMonthView.MAX_CONS_MONTH_VIEW.P_NAME;
    }

    @Override
    public UUID component1() {
        return getPUuid();
    }

    @Override
    public Integer component2() {
        return getMaxCons();
    }

    @Override
    public String component3() {
        return getPName();
    }

    @Override
    public UUID value1() {
        return getPUuid();
    }

    @Override
    public Integer value2() {
        return getMaxCons();
    }

    @Override
    public String value3() {
        return getPName();
    }

    @Override
    public MaxConsMonthViewRecord value1(UUID value) {
        setPUuid(value);
        return this;
    }

    @Override
    public MaxConsMonthViewRecord value2(Integer value) {
        setMaxCons(value);
        return this;
    }

    @Override
    public MaxConsMonthViewRecord value3(String value) {
        setPName(value);
        return this;
    }

    @Override
    public MaxConsMonthViewRecord values(UUID value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MaxConsMonthViewRecord
     */
    public MaxConsMonthViewRecord() {
        super(MaxConsMonthView.MAX_CONS_MONTH_VIEW);
    }

    /**
     * Create a detached, initialised MaxConsMonthViewRecord
     */
    public MaxConsMonthViewRecord(UUID pUuid, Integer maxCons, String pName) {
        super(MaxConsMonthView.MAX_CONS_MONTH_VIEW);

        setPUuid(pUuid);
        setMaxCons(maxCons);
        setPName(pName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MaxConsMonthViewRecord
     */
    public MaxConsMonthViewRecord(vc.data.dto.tables.pojos.MaxConsMonthView value) {
        super(MaxConsMonthView.MAX_CONS_MONTH_VIEW);

        if (value != null) {
            setPUuid(value.getPUuid());
            setMaxCons(value.getMaxCons());
            setPName(value.getPName());
            resetChangedOnNotNull();
        }
    }
}
