/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.OnlinePlayers;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OnlinePlayersRecord extends TableRecordImpl<OnlinePlayersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.online_players.player_name</code>.
     */
    public OnlinePlayersRecord setPlayerName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.online_players.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.online_players.player_uuid</code>.
     */
    public OnlinePlayersRecord setPlayerUuid(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.online_players.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.online_players.join_time</code>.
     */
    public OnlinePlayersRecord setJoinTime(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.online_players.join_time</code>.
     */
    public OffsetDateTime getJoinTime() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OnlinePlayersRecord
     */
    public OnlinePlayersRecord() {
        super(OnlinePlayers.ONLINE_PLAYERS);
    }

    /**
     * Create a detached, initialised OnlinePlayersRecord
     */
    public OnlinePlayersRecord(String playerName, UUID playerUuid, OffsetDateTime joinTime) {
        super(OnlinePlayers.ONLINE_PLAYERS);

        setPlayerName(playerName);
        setPlayerUuid(playerUuid);
        setJoinTime(joinTime);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OnlinePlayersRecord
     */
    public OnlinePlayersRecord(vc.data.dto.tables.pojos.OnlinePlayers value) {
        super(OnlinePlayers.ONLINE_PLAYERS);

        if (value != null) {
            setPlayerName(value.getPlayerName());
            setPlayerUuid(value.getPlayerUuid());
            setJoinTime(value.getJoinTime());
            resetChangedOnNotNull();
        }
    }
}
