/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.OnlinePlayers;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OnlinePlayersRecord extends TableRecordImpl<OnlinePlayersRecord> implements Record2<String, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.online_players.player_name</code>.
     */
    public OnlinePlayersRecord setPlayerName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.online_players.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.online_players.player_uuid</code>.
     */
    public OnlinePlayersRecord setPlayerUuid(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.online_players.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return OnlinePlayers.ONLINE_PLAYERS.PLAYER_NAME;
    }

    @Override
    public Field<UUID> field2() {
        return OnlinePlayers.ONLINE_PLAYERS.PLAYER_UUID;
    }

    @Override
    public String component1() {
        return getPlayerName();
    }

    @Override
    public UUID component2() {
        return getPlayerUuid();
    }

    @Override
    public String value1() {
        return getPlayerName();
    }

    @Override
    public UUID value2() {
        return getPlayerUuid();
    }

    @Override
    public OnlinePlayersRecord value1(String value) {
        setPlayerName(value);
        return this;
    }

    @Override
    public OnlinePlayersRecord value2(UUID value) {
        setPlayerUuid(value);
        return this;
    }

    @Override
    public OnlinePlayersRecord values(String value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OnlinePlayersRecord
     */
    public OnlinePlayersRecord() {
        super(OnlinePlayers.ONLINE_PLAYERS);
    }

    /**
     * Create a detached, initialised OnlinePlayersRecord
     */
    public OnlinePlayersRecord(String playerName, UUID playerUuid) {
        super(OnlinePlayers.ONLINE_PLAYERS);

        setPlayerName(playerName);
        setPlayerUuid(playerUuid);
    }

    /**
     * Create a detached, initialised OnlinePlayersRecord
     */
    public OnlinePlayersRecord(vc.data.dto.tables.pojos.OnlinePlayers value) {
        super(OnlinePlayers.ONLINE_PLAYERS);

        if (value != null) {
            setPlayerName(value.getPlayerName());
            setPlayerUuid(value.getPlayerUuid());
        }
    }
}
