/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.PlaytimeMonth;

import java.math.BigDecimal;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaytimeMonthRecord extends TableRecordImpl<PlaytimeMonthRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.playtime_month.player_name</code>.
     */
    public PlaytimeMonthRecord setPlayerName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.playtime_month.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.playtime_month.player_uuid</code>.
     */
    public PlaytimeMonthRecord setPlayerUuid(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.playtime_month.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.playtime_month.playtime_days</code>.
     */
    public PlaytimeMonthRecord setPlaytimeDays(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.playtime_month.playtime_days</code>.
     */
    public BigDecimal getPlaytimeDays() {
        return (BigDecimal) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlaytimeMonthRecord
     */
    public PlaytimeMonthRecord() {
        super(PlaytimeMonth.PLAYTIME_MONTH);
    }

    /**
     * Create a detached, initialised PlaytimeMonthRecord
     */
    public PlaytimeMonthRecord(String playerName, UUID playerUuid, BigDecimal playtimeDays) {
        super(PlaytimeMonth.PLAYTIME_MONTH);

        setPlayerName(playerName);
        setPlayerUuid(playerUuid);
        setPlaytimeDays(playtimeDays);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PlaytimeMonthRecord
     */
    public PlaytimeMonthRecord(vc.data.dto.tables.pojos.PlaytimeMonth value) {
        super(PlaytimeMonth.PLAYTIME_MONTH);

        if (value != null) {
            setPlayerName(value.getPlayerName());
            setPlayerUuid(value.getPlayerUuid());
            setPlaytimeDays(value.getPlaytimeDays());
            resetChangedOnNotNull();
        }
    }
}
