/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.PlaytimeMonthView;

import java.math.BigDecimal;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaytimeMonthViewRecord extends TableRecordImpl<PlaytimeMonthViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.playtime_month_view.p_uuid</code>.
     */
    public PlaytimeMonthViewRecord setPUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.playtime_month_view.p_uuid</code>.
     */
    public UUID getPUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.playtime_month_view.pt_days</code>.
     */
    public PlaytimeMonthViewRecord setPtDays(BigDecimal value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.playtime_month_view.pt_days</code>.
     */
    public BigDecimal getPtDays() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.playtime_month_view.p_name</code>.
     */
    public PlaytimeMonthViewRecord setPName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.playtime_month_view.p_name</code>.
     */
    public String getPName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlaytimeMonthViewRecord
     */
    public PlaytimeMonthViewRecord() {
        super(PlaytimeMonthView.PLAYTIME_MONTH_VIEW);
    }

    /**
     * Create a detached, initialised PlaytimeMonthViewRecord
     */
    public PlaytimeMonthViewRecord(UUID pUuid, BigDecimal ptDays, String pName) {
        super(PlaytimeMonthView.PLAYTIME_MONTH_VIEW);

        setPUuid(pUuid);
        setPtDays(ptDays);
        setPName(pName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PlaytimeMonthViewRecord
     */
    public PlaytimeMonthViewRecord(vc.data.dto.tables.pojos.PlaytimeMonthView value) {
        super(PlaytimeMonthView.PLAYTIME_MONTH_VIEW);

        if (value != null) {
            setPUuid(value.getPUuid());
            setPtDays(value.getPtDays());
            setPName(value.getPName());
            resetChangedOnNotNull();
        }
    }
}
