/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import vc.data.dto.tables.Playtime;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaytimeRecord extends UpdatableRecordImpl<PlaytimeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.playtime.id</code>.
     */
    public PlaytimeRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.playtime.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.playtime.player_uuid</code>.
     */
    public PlaytimeRecord setPlayerUuid(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.playtime.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.playtime.player_name</code>.
     */
    public PlaytimeRecord setPlayerName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.playtime.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.playtime.playtime_seconds</code>.
     */
    public PlaytimeRecord setPlaytimeSeconds(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.playtime.playtime_seconds</code>.
     */
    public Integer getPlaytimeSeconds() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.playtime.start_time</code>.
     */
    public PlaytimeRecord setStartTime(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.playtime.start_time</code>.
     */
    public OffsetDateTime getStartTime() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.playtime.end_time</code>.
     */
    public PlaytimeRecord setEndTime(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.playtime.end_time</code>.
     */
    public OffsetDateTime getEndTime() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlaytimeRecord
     */
    public PlaytimeRecord() {
        super(Playtime.PLAYTIME);
    }

    /**
     * Create a detached, initialised PlaytimeRecord
     */
    public PlaytimeRecord(Long id, UUID playerUuid, String playerName, Integer playtimeSeconds, OffsetDateTime startTime, OffsetDateTime endTime) {
        super(Playtime.PLAYTIME);

        setId(id);
        setPlayerUuid(playerUuid);
        setPlayerName(playerName);
        setPlaytimeSeconds(playtimeSeconds);
        setStartTime(startTime);
        setEndTime(endTime);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PlaytimeRecord
     */
    public PlaytimeRecord(vc.data.dto.tables.pojos.Playtime value) {
        super(Playtime.PLAYTIME);

        if (value != null) {
            setId(value.getId());
            setPlayerUuid(value.getPlayerUuid());
            setPlayerName(value.getPlayerName());
            setPlaytimeSeconds(value.getPlaytimeSeconds());
            setStartTime(value.getStartTime());
            setEndTime(value.getEndTime());
            resetChangedOnNotNull();
        }
    }
}
