/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.PlayerStats;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerStatsRecord extends TableRecordImpl<PlayerStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.player_stats.join_count</code>.
     */
    public PlayerStatsRecord setJoinCount(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.player_stats.join_count</code>.
     */
    public Long getJoinCount() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.player_stats.leave_count</code>.
     */
    public PlayerStatsRecord setLeaveCount(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.player_stats.leave_count</code>.
     */
    public Long getLeaveCount() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.player_stats.death_count</code>.
     */
    public PlayerStatsRecord setDeathCount(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.player_stats.death_count</code>.
     */
    public Long getDeathCount() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.player_stats.kill_count</code>.
     */
    public PlayerStatsRecord setKillCount(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.player_stats.kill_count</code>.
     */
    public Long getKillCount() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.player_stats.first_seen</code>.
     */
    public PlayerStatsRecord setFirstSeen(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.player_stats.first_seen</code>.
     */
    public OffsetDateTime getFirstSeen() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.player_stats.last_seen</code>.
     */
    public PlayerStatsRecord setLastSeen(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.player_stats.last_seen</code>.
     */
    public OffsetDateTime getLastSeen() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.player_stats.playtime</code>.
     */
    public PlayerStatsRecord setPlaytime(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.player_stats.playtime</code>.
     */
    public Integer getPlaytime() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.player_stats.playtime_30_days</code>.
     */
    public PlayerStatsRecord setPlaytime_30Days(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.player_stats.playtime_30_days</code>.
     */
    public Integer getPlaytime_30Days() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.player_stats.chats_count</code>.
     */
    public PlayerStatsRecord setChatsCount(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.player_stats.chats_count</code>.
     */
    public Long getChatsCount() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerStatsRecord
     */
    public PlayerStatsRecord() {
        super(PlayerStats.PLAYER_STATS);
    }

    /**
     * Create a detached, initialised PlayerStatsRecord
     */
    public PlayerStatsRecord(Long joinCount, Long leaveCount, Long deathCount, Long killCount, OffsetDateTime firstSeen, OffsetDateTime lastSeen, Integer playtime, Integer playtime_30Days, Long chatsCount) {
        super(PlayerStats.PLAYER_STATS);

        setJoinCount(joinCount);
        setLeaveCount(leaveCount);
        setDeathCount(deathCount);
        setKillCount(killCount);
        setFirstSeen(firstSeen);
        setLastSeen(lastSeen);
        setPlaytime(playtime);
        setPlaytime_30Days(playtime_30Days);
        setChatsCount(chatsCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PlayerStatsRecord
     */
    public PlayerStatsRecord(vc.data.dto.tables.pojos.PlayerStats value) {
        super(PlayerStats.PLAYER_STATS);

        if (value != null) {
            setJoinCount(value.getJoinCount());
            setLeaveCount(value.getLeaveCount());
            setDeathCount(value.getDeathCount());
            setKillCount(value.getKillCount());
            setFirstSeen(value.getFirstSeen());
            setLastSeen(value.getLastSeen());
            setPlaytime(value.getPlaytime());
            setPlaytime_30Days(value.getPlaytime_30Days());
            setChatsCount(value.getChatsCount());
            resetChangedOnNotNull();
        }
    }
}
