/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.PlaytimeAllMonth;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlaytimeAllMonthRecord extends TableRecordImpl<PlaytimeAllMonthRecord> implements Record3<UUID, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.playtime_all_month.p_uuid</code>.
     */
    public PlaytimeAllMonthRecord setPUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.playtime_all_month.p_uuid</code>.
     */
    public UUID getPUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.playtime_all_month.playtime</code>.
     */
    public PlaytimeAllMonthRecord setPlaytime(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.playtime_all_month.playtime</code>.
     */
    public Integer getPlaytime() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.playtime_all_month.p_name</code>.
     */
    public PlaytimeAllMonthRecord setPName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.playtime_all_month.p_name</code>.
     */
    public String getPName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return PlaytimeAllMonth.PLAYTIME_ALL_MONTH.P_UUID;
    }

    @Override
    public Field<Integer> field2() {
        return PlaytimeAllMonth.PLAYTIME_ALL_MONTH.PLAYTIME;
    }

    @Override
    public Field<String> field3() {
        return PlaytimeAllMonth.PLAYTIME_ALL_MONTH.P_NAME;
    }

    @Override
    public UUID component1() {
        return getPUuid();
    }

    @Override
    public Integer component2() {
        return getPlaytime();
    }

    @Override
    public String component3() {
        return getPName();
    }

    @Override
    public UUID value1() {
        return getPUuid();
    }

    @Override
    public Integer value2() {
        return getPlaytime();
    }

    @Override
    public String value3() {
        return getPName();
    }

    @Override
    public PlaytimeAllMonthRecord value1(UUID value) {
        setPUuid(value);
        return this;
    }

    @Override
    public PlaytimeAllMonthRecord value2(Integer value) {
        setPlaytime(value);
        return this;
    }

    @Override
    public PlaytimeAllMonthRecord value3(String value) {
        setPName(value);
        return this;
    }

    @Override
    public PlaytimeAllMonthRecord values(UUID value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlaytimeAllMonthRecord
     */
    public PlaytimeAllMonthRecord() {
        super(PlaytimeAllMonth.PLAYTIME_ALL_MONTH);
    }

    /**
     * Create a detached, initialised PlaytimeAllMonthRecord
     */
    public PlaytimeAllMonthRecord(UUID pUuid, Integer playtime, String pName) {
        super(PlaytimeAllMonth.PLAYTIME_ALL_MONTH);

        setPUuid(pUuid);
        setPlaytime(playtime);
        setPName(pName);
    }

    /**
     * Create a detached, initialised PlaytimeAllMonthRecord
     */
    public PlaytimeAllMonthRecord(vc.data.dto.tables.pojos.PlaytimeAllMonth value) {
        super(PlaytimeAllMonth.PLAYTIME_ALL_MONTH);

        if (value != null) {
            setPUuid(value.getPUuid());
            setPlaytime(value.getPlaytime());
            setPName(value.getPName());
        }
    }
}
