/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.PriorityPlayers;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PriorityPlayersRecord extends TableRecordImpl<PriorityPlayersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.priority_players.player_uuid</code>.
     */
    public PriorityPlayersRecord setPlayerUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.priority_players.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.priority_players.player_name</code>.
     */
    public PriorityPlayersRecord setPlayerName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.priority_players.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.priority_players.priority_joins</code>.
     */
    public PriorityPlayersRecord setPriorityJoins(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.priority_players.priority_joins</code>.
     */
    public Long getPriorityJoins() {
        return (Long) get(2);
    }

    /**
     * Setter for
     * <code>public.priority_players.priority_session_length_count</code>.
     */
    public PriorityPlayersRecord setPrioritySessionLengthCount(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.priority_players.priority_session_length_count</code>.
     */
    public Long getPrioritySessionLengthCount() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PriorityPlayersRecord
     */
    public PriorityPlayersRecord() {
        super(PriorityPlayers.PRIORITY_PLAYERS);
    }

    /**
     * Create a detached, initialised PriorityPlayersRecord
     */
    public PriorityPlayersRecord(UUID playerUuid, String playerName, Long priorityJoins, Long prioritySessionLengthCount) {
        super(PriorityPlayers.PRIORITY_PLAYERS);

        setPlayerUuid(playerUuid);
        setPlayerName(playerName);
        setPriorityJoins(priorityJoins);
        setPrioritySessionLengthCount(prioritySessionLengthCount);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised PriorityPlayersRecord
     */
    public PriorityPlayersRecord(vc.data.dto.tables.pojos.PriorityPlayers value) {
        super(PriorityPlayers.PRIORITY_PLAYERS);

        if (value != null) {
            setPlayerUuid(value.getPlayerUuid());
            setPlayerName(value.getPlayerName());
            setPriorityJoins(value.getPriorityJoins());
            setPrioritySessionLengthCount(value.getPrioritySessionLengthCount());
            resetTouchedOnNotNull();
        }
    }
}
