/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.PriorityPlayersView;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PriorityPlayersViewRecord extends TableRecordImpl<PriorityPlayersViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.priority_players_view.player_name</code>.
     */
    public PriorityPlayersViewRecord setPlayerName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.priority_players_view.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.priority_players_view.player_uuid</code>.
     */
    public PriorityPlayersViewRecord setPlayerUuid(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.priority_players_view.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.priority_players_view.priority_joins</code>.
     */
    public PriorityPlayersViewRecord setPriorityJoins(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.priority_players_view.priority_joins</code>.
     */
    public Long getPriorityJoins() {
        return (Long) get(2);
    }

    /**
     * Setter for
     * <code>public.priority_players_view.priority_session_length_count</code>.
     */
    public PriorityPlayersViewRecord setPrioritySessionLengthCount(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.priority_players_view.priority_session_length_count</code>.
     */
    public Long getPrioritySessionLengthCount() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PriorityPlayersViewRecord
     */
    public PriorityPlayersViewRecord() {
        super(PriorityPlayersView.PRIORITY_PLAYERS_VIEW);
    }

    /**
     * Create a detached, initialised PriorityPlayersViewRecord
     */
    public PriorityPlayersViewRecord(String playerName, UUID playerUuid, Long priorityJoins, Long prioritySessionLengthCount) {
        super(PriorityPlayersView.PRIORITY_PLAYERS_VIEW);

        setPlayerName(playerName);
        setPlayerUuid(playerUuid);
        setPriorityJoins(priorityJoins);
        setPrioritySessionLengthCount(prioritySessionLengthCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PriorityPlayersViewRecord
     */
    public PriorityPlayersViewRecord(vc.data.dto.tables.pojos.PriorityPlayersView value) {
        super(PriorityPlayersView.PRIORITY_PLAYERS_VIEW);

        if (value != null) {
            setPlayerName(value.getPlayerName());
            setPlayerUuid(value.getPlayerUuid());
            setPriorityJoins(value.getPriorityJoins());
            setPrioritySessionLengthCount(value.getPrioritySessionLengthCount());
            resetChangedOnNotNull();
        }
    }
}
