/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import vc.data.dto.tables.TablistText;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TablistTextRecord extends UpdatableRecordImpl<TablistTextRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tablist_text.id</code>.
     */
    public TablistTextRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist_text.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tablist_text.time</code>.
     */
    public TablistTextRecord setTime(OffsetDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist_text.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.tablist_text.header_text</code>.
     */
    public TablistTextRecord setHeaderText(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist_text.header_text</code>.
     */
    public String getHeaderText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tablist_text.header_json</code>.
     */
    public TablistTextRecord setHeaderJson(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist_text.header_json</code>.
     */
    public String getHeaderJson() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tablist_text.footer_text</code>.
     */
    public TablistTextRecord setFooterText(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist_text.footer_text</code>.
     */
    public String getFooterText() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tablist_text.footer_json</code>.
     */
    public TablistTextRecord setFooterJson(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist_text.footer_json</code>.
     */
    public String getFooterJson() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TablistTextRecord
     */
    public TablistTextRecord() {
        super(TablistText.TABLIST_TEXT);
    }

    /**
     * Create a detached, initialised TablistTextRecord
     */
    public TablistTextRecord(Long id, OffsetDateTime time, String headerText, String headerJson, String footerText, String footerJson) {
        super(TablistText.TABLIST_TEXT);

        setId(id);
        setTime(time);
        setHeaderText(headerText);
        setHeaderJson(headerJson);
        setFooterText(footerText);
        setFooterJson(footerJson);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised TablistTextRecord
     */
    public TablistTextRecord(vc.data.dto.tables.pojos.TablistText value) {
        super(TablistText.TABLIST_TEXT);

        if (value != null) {
            setId(value.getId());
            setTime(value.getTime());
            setHeaderText(value.getHeaderText());
            setHeaderJson(value.getHeaderJson());
            setFooterText(value.getFooterText());
            setFooterJson(value.getFooterJson());
            resetTouchedOnNotNull();
        }
    }
}
