/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.TablistInfo;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TablistInfoRecord extends TableRecordImpl<TablistInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tablist_info.player_name</code>.
     */
    public TablistInfoRecord setPlayerName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist_info.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.tablist_info.player_uuid</code>.
     */
    public TablistInfoRecord setPlayerUuid(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist_info.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.tablist_info.prio</code>.
     */
    public TablistInfoRecord setPrio(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist_info.prio</code>.
     */
    public Boolean getPrio() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.tablist_info.is_bot</code>.
     */
    public TablistInfoRecord setIsBot(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist_info.is_bot</code>.
     */
    public Boolean getIsBot() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TablistInfoRecord
     */
    public TablistInfoRecord() {
        super(TablistInfo.TABLIST_INFO);
    }

    /**
     * Create a detached, initialised TablistInfoRecord
     */
    public TablistInfoRecord(String playerName, UUID playerUuid, Boolean prio, Boolean isBot) {
        super(TablistInfo.TABLIST_INFO);

        setPlayerName(playerName);
        setPlayerUuid(playerUuid);
        setPrio(prio);
        setIsBot(isBot);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TablistInfoRecord
     */
    public TablistInfoRecord(vc.data.dto.tables.pojos.TablistInfo value) {
        super(TablistInfo.TABLIST_INFO);

        if (value != null) {
            setPlayerName(value.getPlayerName());
            setPlayerUuid(value.getPlayerUuid());
            setPrio(value.getPrio());
            setIsBot(value.getIsBot());
            resetChangedOnNotNull();
        }
    }
}
