/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.TopDeathsMonthView;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TopDeathsMonthViewRecord extends TableRecordImpl<TopDeathsMonthViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.top_deaths_month_view.victim_player_name</code>.
     */
    public TopDeathsMonthViewRecord setVictimPlayerName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.top_deaths_month_view.victim_player_name</code>.
     */
    public String getVictimPlayerName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.top_deaths_month_view.victim_player_uuid</code>.
     */
    public TopDeathsMonthViewRecord setVictimPlayerUuid(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.top_deaths_month_view.victim_player_uuid</code>.
     */
    public UUID getVictimPlayerUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.top_deaths_month_view.death_count</code>.
     */
    public TopDeathsMonthViewRecord setDeathCount(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.top_deaths_month_view.death_count</code>.
     */
    public Long getDeathCount() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TopDeathsMonthViewRecord
     */
    public TopDeathsMonthViewRecord() {
        super(TopDeathsMonthView.TOP_DEATHS_MONTH_VIEW);
    }

    /**
     * Create a detached, initialised TopDeathsMonthViewRecord
     */
    public TopDeathsMonthViewRecord(String victimPlayerName, UUID victimPlayerUuid, Long deathCount) {
        super(TopDeathsMonthView.TOP_DEATHS_MONTH_VIEW);

        setVictimPlayerName(victimPlayerName);
        setVictimPlayerUuid(victimPlayerUuid);
        setDeathCount(deathCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TopDeathsMonthViewRecord
     */
    public TopDeathsMonthViewRecord(vc.data.dto.tables.pojos.TopDeathsMonthView value) {
        super(TopDeathsMonthView.TOP_DEATHS_MONTH_VIEW);

        if (value != null) {
            setVictimPlayerName(value.getVictimPlayerName());
            setVictimPlayerUuid(value.getVictimPlayerUuid());
            setDeathCount(value.getDeathCount());
            resetChangedOnNotNull();
        }
    }
}
