/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.TopKillsMonthView;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TopKillsMonthViewRecord extends TableRecordImpl<TopKillsMonthViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.top_kills_month_view.killer_player_name</code>.
     */
    public TopKillsMonthViewRecord setKillerPlayerName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.top_kills_month_view.killer_player_name</code>.
     */
    public String getKillerPlayerName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.top_kills_month_view.killer_player_uuid</code>.
     */
    public TopKillsMonthViewRecord setKillerPlayerUuid(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.top_kills_month_view.killer_player_uuid</code>.
     */
    public UUID getKillerPlayerUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.top_kills_month_view.kill_count</code>.
     */
    public TopKillsMonthViewRecord setKillCount(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.top_kills_month_view.kill_count</code>.
     */
    public Long getKillCount() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TopKillsMonthViewRecord
     */
    public TopKillsMonthViewRecord() {
        super(TopKillsMonthView.TOP_KILLS_MONTH_VIEW);
    }

    /**
     * Create a detached, initialised TopKillsMonthViewRecord
     */
    public TopKillsMonthViewRecord(String killerPlayerName, UUID killerPlayerUuid, Long killCount) {
        super(TopKillsMonthView.TOP_KILLS_MONTH_VIEW);

        setKillerPlayerName(killerPlayerName);
        setKillerPlayerUuid(killerPlayerUuid);
        setKillCount(killCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TopKillsMonthViewRecord
     */
    public TopKillsMonthViewRecord(vc.data.dto.tables.pojos.TopKillsMonthView value) {
        super(TopKillsMonthView.TOP_KILLS_MONTH_VIEW);

        if (value != null) {
            setKillerPlayerName(value.getKillerPlayerName());
            setKillerPlayerUuid(value.getKillerPlayerUuid());
            setKillCount(value.getKillCount());
            resetChangedOnNotNull();
        }
    }
}
