/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.TopPlaytimeAllTimeView;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TopPlaytimeAllTimeViewRecord extends TableRecordImpl<TopPlaytimeAllTimeViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.top_playtime_all_time_view.player_uuid</code>.
     */
    public TopPlaytimeAllTimeViewRecord setPlayerUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.top_playtime_all_time_view.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.top_playtime_all_time_view.player_name</code>.
     */
    public TopPlaytimeAllTimeViewRecord setPlayerName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.top_playtime_all_time_view.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>public.top_playtime_all_time_view.playtime_seconds</code>.
     */
    public TopPlaytimeAllTimeViewRecord setPlaytimeSeconds(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.top_playtime_all_time_view.playtime_seconds</code>.
     */
    public Long getPlaytimeSeconds() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TopPlaytimeAllTimeViewRecord
     */
    public TopPlaytimeAllTimeViewRecord() {
        super(TopPlaytimeAllTimeView.TOP_PLAYTIME_ALL_TIME_VIEW);
    }

    /**
     * Create a detached, initialised TopPlaytimeAllTimeViewRecord
     */
    public TopPlaytimeAllTimeViewRecord(UUID playerUuid, String playerName, Long playtimeSeconds) {
        super(TopPlaytimeAllTimeView.TOP_PLAYTIME_ALL_TIME_VIEW);

        setPlayerUuid(playerUuid);
        setPlayerName(playerName);
        setPlaytimeSeconds(playtimeSeconds);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised TopPlaytimeAllTimeViewRecord
     */
    public TopPlaytimeAllTimeViewRecord(vc.data.dto.tables.pojos.TopPlaytimeAllTimeView value) {
        super(TopPlaytimeAllTimeView.TOP_PLAYTIME_ALL_TIME_VIEW);

        if (value != null) {
            setPlayerUuid(value.getPlayerUuid());
            setPlayerName(value.getPlayerName());
            setPlaytimeSeconds(value.getPlaytimeSeconds());
            resetTouchedOnNotNull();
        }
    }
}
