/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.TopPlaytimeMonthView;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TopPlaytimeMonthViewRecord extends TableRecordImpl<TopPlaytimeMonthViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.top_playtime_month_view.player_uuid</code>.
     */
    public TopPlaytimeMonthViewRecord setPlayerUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.top_playtime_month_view.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.top_playtime_month_view.player_name</code>.
     */
    public TopPlaytimeMonthViewRecord setPlayerName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.top_playtime_month_view.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.top_playtime_month_view.playtime_seconds</code>.
     */
    public TopPlaytimeMonthViewRecord setPlaytimeSeconds(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.top_playtime_month_view.playtime_seconds</code>.
     */
    public Long getPlaytimeSeconds() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TopPlaytimeMonthViewRecord
     */
    public TopPlaytimeMonthViewRecord() {
        super(TopPlaytimeMonthView.TOP_PLAYTIME_MONTH_VIEW);
    }

    /**
     * Create a detached, initialised TopPlaytimeMonthViewRecord
     */
    public TopPlaytimeMonthViewRecord(UUID playerUuid, String playerName, Long playtimeSeconds) {
        super(TopPlaytimeMonthView.TOP_PLAYTIME_MONTH_VIEW);

        setPlayerUuid(playerUuid);
        setPlayerName(playerName);
        setPlaytimeSeconds(playtimeSeconds);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TopPlaytimeMonthViewRecord
     */
    public TopPlaytimeMonthViewRecord(vc.data.dto.tables.pojos.TopPlaytimeMonthView value) {
        super(TopPlaytimeMonthView.TOP_PLAYTIME_MONTH_VIEW);

        if (value != null) {
            setPlayerUuid(value.getPlayerUuid());
            setPlayerName(value.getPlayerName());
            setPlaytimeSeconds(value.getPlaytimeSeconds());
            resetChangedOnNotNull();
        }
    }
}
