/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.records;


import org.jooq.impl.TableRecordImpl;
import vc.data.dto.tables.Worldtime;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorldtimeRecord extends TableRecordImpl<WorldtimeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.worldtime.time</code>.
     */
    public WorldtimeRecord setTime(OffsetDateTime value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.worldtime.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(0);
    }

    /**
     * Setter for <code>public.worldtime.worldage</code>.
     */
    public WorldtimeRecord setWorldage(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.worldtime.worldage</code>.
     */
    public Long getWorldage() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.worldtime.worldtime</code>.
     */
    public WorldtimeRecord setWorldtime(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.worldtime.worldtime</code>.
     */
    public Long getWorldtime() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorldtimeRecord
     */
    public WorldtimeRecord() {
        super(Worldtime.WORLDTIME);
    }

    /**
     * Create a detached, initialised WorldtimeRecord
     */
    public WorldtimeRecord(OffsetDateTime time, Long worldage, Long worldtime) {
        super(Worldtime.WORLDTIME);

        setTime(time);
        setWorldage(worldage);
        setWorldtime(worldtime);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised WorldtimeRecord
     */
    public WorldtimeRecord(vc.data.dto.tables.pojos.Worldtime value) {
        super(Worldtime.WORLDTIME);

        if (value != null) {
            setTime(value.getTime());
            setWorldage(value.getWorldage());
            setWorldtime(value.getWorldtime());
            resetTouchedOnNotNull();
        }
    }
}
