/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FirstSeen implements Serializable {

    private static final long serialVersionUID = 1L;

    private final OffsetDateTime firstSeen;

    public FirstSeen(FirstSeen value) {
        this.firstSeen = value.firstSeen;
    }

    public FirstSeen(
        OffsetDateTime firstSeen
    ) {
        this.firstSeen = firstSeen;
    }

    /**
     * Getter for <code>public.first_seen.first_seen</code>.
     */
    public OffsetDateTime getFirstSeen() {
        return this.firstSeen;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FirstSeen other = (FirstSeen) obj;
        if (this.firstSeen == null) {
            if (other.firstSeen != null)
                return false;
        }
        else if (!this.firstSeen.equals(other.firstSeen))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.firstSeen == null) ? 0 : this.firstSeen.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FirstSeen (");

        sb.append(firstSeen);

        sb.append(")");
        return sb.toString();
    }
}
