/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GetUuidData implements Serializable {

    private static final long serialVersionUID = 1L;

    private final OffsetDateTime time;
    private final String data;
    private final String tableName;

    public GetUuidData(GetUuidData value) {
        this.time = value.time;
        this.data = value.data;
        this.tableName = value.tableName;
    }

    public GetUuidData(
        OffsetDateTime time,
        String data,
        String tableName
    ) {
        this.time = time;
        this.data = data;
        this.tableName = tableName;
    }

    /**
     * Getter for <code>public.get_uuid_data.time</code>.
     */
    public OffsetDateTime getTime() {
        return this.time;
    }

    /**
     * Getter for <code>public.get_uuid_data.data</code>.
     */
    public String getData() {
        return this.data;
    }

    /**
     * Getter for <code>public.get_uuid_data.table_name</code>.
     */
    public String getTableName() {
        return this.tableName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GetUuidData other = (GetUuidData) obj;
        if (this.time == null) {
            if (other.time != null)
                return false;
        }
        else if (!this.time.equals(other.time))
            return false;
        if (this.data == null) {
            if (other.data != null)
                return false;
        }
        else if (!this.data.equals(other.data))
            return false;
        if (this.tableName == null) {
            if (other.tableName != null)
                return false;
        }
        else if (!this.tableName.equals(other.tableName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.time == null) ? 0 : this.time.hashCode());
        result = prime * result + ((this.data == null) ? 0 : this.data.hashCode());
        result = prime * result + ((this.tableName == null) ? 0 : this.tableName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GetUuidData (");

        sb.append(time);
        sb.append(", ").append(data);
        sb.append(", ").append(tableName);

        sb.append(")");
        return sb.toString();
    }
}
