/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LastSeen implements Serializable {

    private static final long serialVersionUID = 1L;

    private final OffsetDateTime lastSeen;

    public LastSeen(LastSeen value) {
        this.lastSeen = value.lastSeen;
    }

    public LastSeen(
        OffsetDateTime lastSeen
    ) {
        this.lastSeen = lastSeen;
    }

    /**
     * Getter for <code>public.last_seen.last_seen</code>.
     */
    public OffsetDateTime getLastSeen() {
        return this.lastSeen;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LastSeen other = (LastSeen) obj;
        if (this.lastSeen == null) {
            if (other.lastSeen != null)
                return false;
        }
        else if (!this.lastSeen.equals(other.lastSeen))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.lastSeen == null) ? 0 : this.lastSeen.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LastSeen (");

        sb.append(lastSeen);

        sb.append(")");
        return sb.toString();
    }
}
