/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Names implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String name;
    private final UUID uuid;
    private final OffsetDateTime changedtoat;
    private final OffsetDateTime changedfromat;

    public Names(Names value) {
        this.name = value.name;
        this.uuid = value.uuid;
        this.changedtoat = value.changedtoat;
        this.changedfromat = value.changedfromat;
    }

    public Names(
        String name,
        UUID uuid,
        OffsetDateTime changedtoat,
        OffsetDateTime changedfromat
    ) {
        this.name = name;
        this.uuid = uuid;
        this.changedtoat = changedtoat;
        this.changedfromat = changedfromat;
    }

    /**
     * Getter for <code>public.names.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.names.uuid</code>.
     */
    public UUID getUuid() {
        return this.uuid;
    }

    /**
     * Getter for <code>public.names.changedtoat</code>.
     */
    public OffsetDateTime getChangedtoat() {
        return this.changedtoat;
    }

    /**
     * Getter for <code>public.names.changedfromat</code>.
     */
    public OffsetDateTime getChangedfromat() {
        return this.changedfromat;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Names other = (Names) obj;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.uuid == null) {
            if (other.uuid != null)
                return false;
        }
        else if (!this.uuid.equals(other.uuid))
            return false;
        if (this.changedtoat == null) {
            if (other.changedtoat != null)
                return false;
        }
        else if (!this.changedtoat.equals(other.changedtoat))
            return false;
        if (this.changedfromat == null) {
            if (other.changedfromat != null)
                return false;
        }
        else if (!this.changedfromat.equals(other.changedfromat))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.uuid == null) ? 0 : this.uuid.hashCode());
        result = prime * result + ((this.changedtoat == null) ? 0 : this.changedtoat.hashCode());
        result = prime * result + ((this.changedfromat == null) ? 0 : this.changedfromat.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Names (");

        sb.append(name);
        sb.append(", ").append(uuid);
        sb.append(", ").append(changedtoat);
        sb.append(", ").append(changedfromat);

        sb.append(")");
        return sb.toString();
    }
}
