/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaytimeAllMonth implements Serializable {

    private static final long serialVersionUID = 1L;

    private final UUID pUuid;
    private final Integer playtime;
    private final String pName;

    public PlaytimeAllMonth(PlaytimeAllMonth value) {
        this.pUuid = value.pUuid;
        this.playtime = value.playtime;
        this.pName = value.pName;
    }

    public PlaytimeAllMonth(
        UUID pUuid,
        Integer playtime,
        String pName
    ) {
        this.pUuid = pUuid;
        this.playtime = playtime;
        this.pName = pName;
    }

    /**
     * Getter for <code>public.playtime_all_month.p_uuid</code>.
     */
    public UUID getPUuid() {
        return this.pUuid;
    }

    /**
     * Getter for <code>public.playtime_all_month.playtime</code>.
     */
    public Integer getPlaytime() {
        return this.playtime;
    }

    /**
     * Getter for <code>public.playtime_all_month.p_name</code>.
     */
    public String getPName() {
        return this.pName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PlaytimeAllMonth other = (PlaytimeAllMonth) obj;
        if (this.pUuid == null) {
            if (other.pUuid != null)
                return false;
        }
        else if (!this.pUuid.equals(other.pUuid))
            return false;
        if (this.playtime == null) {
            if (other.playtime != null)
                return false;
        }
        else if (!this.playtime.equals(other.playtime))
            return false;
        if (this.pName == null) {
            if (other.pName != null)
                return false;
        }
        else if (!this.pName.equals(other.pName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.pUuid == null) ? 0 : this.pUuid.hashCode());
        result = prime * result + ((this.playtime == null) ? 0 : this.playtime.hashCode());
        result = prime * result + ((this.pName == null) ? 0 : this.pName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlaytimeAllMonth (");

        sb.append(pUuid);
        sb.append(", ").append(playtime);
        sb.append(", ").append(pName);

        sb.append(")");
        return sb.toString();
    }
}
