/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlaytimeMonthView implements Serializable {

    private static final long serialVersionUID = 1L;

    private final UUID pUuid;
    private final BigDecimal ptDays;
    private final String pName;

    public PlaytimeMonthView(PlaytimeMonthView value) {
        this.pUuid = value.pUuid;
        this.ptDays = value.ptDays;
        this.pName = value.pName;
    }

    public PlaytimeMonthView(
        UUID pUuid,
        BigDecimal ptDays,
        String pName
    ) {
        this.pUuid = pUuid;
        this.ptDays = ptDays;
        this.pName = pName;
    }

    /**
     * Getter for <code>public.playtime_month_view.p_uuid</code>.
     */
    public UUID getPUuid() {
        return this.pUuid;
    }

    /**
     * Getter for <code>public.playtime_month_view.pt_days</code>.
     */
    public BigDecimal getPtDays() {
        return this.ptDays;
    }

    /**
     * Getter for <code>public.playtime_month_view.p_name</code>.
     */
    public String getPName() {
        return this.pName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PlaytimeMonthView other = (PlaytimeMonthView) obj;
        if (this.pUuid == null) {
            if (other.pUuid != null)
                return false;
        }
        else if (!this.pUuid.equals(other.pUuid))
            return false;
        if (this.ptDays == null) {
            if (other.ptDays != null)
                return false;
        }
        else if (!this.ptDays.equals(other.ptDays))
            return false;
        if (this.pName == null) {
            if (other.pName != null)
                return false;
        }
        else if (!this.pName.equals(other.pName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.pUuid == null) ? 0 : this.pUuid.hashCode());
        result = prime * result + ((this.ptDays == null) ? 0 : this.ptDays.hashCode());
        result = prime * result + ((this.pName == null) ? 0 : this.pName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlaytimeMonthView (");

        sb.append(pUuid);
        sb.append(", ").append(ptDays);
        sb.append(", ").append(pName);

        sb.append(")");
        return sb.toString();
    }
}
