/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Playtime implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final UUID playerUuid;
    private final String playerName;
    private final Integer playtimeSeconds;
    private final OffsetDateTime startTime;
    private final OffsetDateTime endTime;

    public Playtime(Playtime value) {
        this.id = value.id;
        this.playerUuid = value.playerUuid;
        this.playerName = value.playerName;
        this.playtimeSeconds = value.playtimeSeconds;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
    }

    public Playtime(
        Long id,
        UUID playerUuid,
        String playerName,
        Integer playtimeSeconds,
        OffsetDateTime startTime,
        OffsetDateTime endTime
    ) {
        this.id = id;
        this.playerUuid = playerUuid;
        this.playerName = playerName;
        this.playtimeSeconds = playtimeSeconds;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    /**
     * Getter for <code>public.playtime.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.playtime.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return this.playerUuid;
    }

    /**
     * Getter for <code>public.playtime.player_name</code>.
     */
    public String getPlayerName() {
        return this.playerName;
    }

    /**
     * Getter for <code>public.playtime.playtime_seconds</code>.
     */
    public Integer getPlaytimeSeconds() {
        return this.playtimeSeconds;
    }

    /**
     * Getter for <code>public.playtime.start_time</code>.
     */
    public OffsetDateTime getStartTime() {
        return this.startTime;
    }

    /**
     * Getter for <code>public.playtime.end_time</code>.
     */
    public OffsetDateTime getEndTime() {
        return this.endTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Playtime other = (Playtime) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.playerUuid == null) {
            if (other.playerUuid != null)
                return false;
        }
        else if (!this.playerUuid.equals(other.playerUuid))
            return false;
        if (this.playerName == null) {
            if (other.playerName != null)
                return false;
        }
        else if (!this.playerName.equals(other.playerName))
            return false;
        if (this.playtimeSeconds == null) {
            if (other.playtimeSeconds != null)
                return false;
        }
        else if (!this.playtimeSeconds.equals(other.playtimeSeconds))
            return false;
        if (this.startTime == null) {
            if (other.startTime != null)
                return false;
        }
        else if (!this.startTime.equals(other.startTime))
            return false;
        if (this.endTime == null) {
            if (other.endTime != null)
                return false;
        }
        else if (!this.endTime.equals(other.endTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.playerUuid == null) ? 0 : this.playerUuid.hashCode());
        result = prime * result + ((this.playerName == null) ? 0 : this.playerName.hashCode());
        result = prime * result + ((this.playtimeSeconds == null) ? 0 : this.playtimeSeconds.hashCode());
        result = prime * result + ((this.startTime == null) ? 0 : this.startTime.hashCode());
        result = prime * result + ((this.endTime == null) ? 0 : this.endTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Playtime (");

        sb.append(id);
        sb.append(", ").append(playerUuid);
        sb.append(", ").append(playerName);
        sb.append(", ").append(playtimeSeconds);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);

        sb.append(")");
        return sb.toString();
    }
}
