/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaytimeMonth implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String playerName;
    private final UUID playerUuid;
    private final BigDecimal playtimeDays;

    public PlaytimeMonth(PlaytimeMonth value) {
        this.playerName = value.playerName;
        this.playerUuid = value.playerUuid;
        this.playtimeDays = value.playtimeDays;
    }

    public PlaytimeMonth(
        String playerName,
        UUID playerUuid,
        BigDecimal playtimeDays
    ) {
        this.playerName = playerName;
        this.playerUuid = playerUuid;
        this.playtimeDays = playtimeDays;
    }

    /**
     * Getter for <code>public.playtime_month.player_name</code>.
     */
    public String getPlayerName() {
        return this.playerName;
    }

    /**
     * Getter for <code>public.playtime_month.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return this.playerUuid;
    }

    /**
     * Getter for <code>public.playtime_month.playtime_days</code>.
     */
    public BigDecimal getPlaytimeDays() {
        return this.playtimeDays;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PlaytimeMonth other = (PlaytimeMonth) obj;
        if (this.playerName == null) {
            if (other.playerName != null)
                return false;
        }
        else if (!this.playerName.equals(other.playerName))
            return false;
        if (this.playerUuid == null) {
            if (other.playerUuid != null)
                return false;
        }
        else if (!this.playerUuid.equals(other.playerUuid))
            return false;
        if (this.playtimeDays == null) {
            if (other.playtimeDays != null)
                return false;
        }
        else if (!this.playtimeDays.equals(other.playtimeDays))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.playerName == null) ? 0 : this.playerName.hashCode());
        result = prime * result + ((this.playerUuid == null) ? 0 : this.playerUuid.hashCode());
        result = prime * result + ((this.playtimeDays == null) ? 0 : this.playtimeDays.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlaytimeMonth (");

        sb.append(playerName);
        sb.append(", ").append(playerUuid);
        sb.append(", ").append(playtimeDays);

        sb.append(")");
        return sb.toString();
    }
}
