/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PriorityPlayersView implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String playerName;
    private final UUID playerUuid;
    private final Long priorityJoins;
    private final Long prioritySessionLengthCount;

    public PriorityPlayersView(PriorityPlayersView value) {
        this.playerName = value.playerName;
        this.playerUuid = value.playerUuid;
        this.priorityJoins = value.priorityJoins;
        this.prioritySessionLengthCount = value.prioritySessionLengthCount;
    }

    public PriorityPlayersView(
        String playerName,
        UUID playerUuid,
        Long priorityJoins,
        Long prioritySessionLengthCount
    ) {
        this.playerName = playerName;
        this.playerUuid = playerUuid;
        this.priorityJoins = priorityJoins;
        this.prioritySessionLengthCount = prioritySessionLengthCount;
    }

    /**
     * Getter for <code>public.priority_players_view.player_name</code>.
     */
    public String getPlayerName() {
        return this.playerName;
    }

    /**
     * Getter for <code>public.priority_players_view.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return this.playerUuid;
    }

    /**
     * Getter for <code>public.priority_players_view.priority_joins</code>.
     */
    public Long getPriorityJoins() {
        return this.priorityJoins;
    }

    /**
     * Getter for
     * <code>public.priority_players_view.priority_session_length_count</code>.
     */
    public Long getPrioritySessionLengthCount() {
        return this.prioritySessionLengthCount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PriorityPlayersView other = (PriorityPlayersView) obj;
        if (this.playerName == null) {
            if (other.playerName != null)
                return false;
        }
        else if (!this.playerName.equals(other.playerName))
            return false;
        if (this.playerUuid == null) {
            if (other.playerUuid != null)
                return false;
        }
        else if (!this.playerUuid.equals(other.playerUuid))
            return false;
        if (this.priorityJoins == null) {
            if (other.priorityJoins != null)
                return false;
        }
        else if (!this.priorityJoins.equals(other.priorityJoins))
            return false;
        if (this.prioritySessionLengthCount == null) {
            if (other.prioritySessionLengthCount != null)
                return false;
        }
        else if (!this.prioritySessionLengthCount.equals(other.prioritySessionLengthCount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.playerName == null) ? 0 : this.playerName.hashCode());
        result = prime * result + ((this.playerUuid == null) ? 0 : this.playerUuid.hashCode());
        result = prime * result + ((this.priorityJoins == null) ? 0 : this.priorityJoins.hashCode());
        result = prime * result + ((this.prioritySessionLengthCount == null) ? 0 : this.prioritySessionLengthCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PriorityPlayersView (");

        sb.append(playerName);
        sb.append(", ").append(playerUuid);
        sb.append(", ").append(priorityJoins);
        sb.append(", ").append(prioritySessionLengthCount);

        sb.append(")");
        return sb.toString();
    }
}
