/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TablistInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String playerName;
    private final UUID playerUuid;
    private final Boolean prio;
    private final Boolean isBot;

    public TablistInfo(TablistInfo value) {
        this.playerName = value.playerName;
        this.playerUuid = value.playerUuid;
        this.prio = value.prio;
        this.isBot = value.isBot;
    }

    public TablistInfo(
        String playerName,
        UUID playerUuid,
        Boolean prio,
        Boolean isBot
    ) {
        this.playerName = playerName;
        this.playerUuid = playerUuid;
        this.prio = prio;
        this.isBot = isBot;
    }

    /**
     * Getter for <code>public.tablist_info.player_name</code>.
     */
    public String getPlayerName() {
        return this.playerName;
    }

    /**
     * Getter for <code>public.tablist_info.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return this.playerUuid;
    }

    /**
     * Getter for <code>public.tablist_info.prio</code>.
     */
    public Boolean getPrio() {
        return this.prio;
    }

    /**
     * Getter for <code>public.tablist_info.is_bot</code>.
     */
    public Boolean getIsBot() {
        return this.isBot;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TablistInfo other = (TablistInfo) obj;
        if (this.playerName == null) {
            if (other.playerName != null)
                return false;
        }
        else if (!this.playerName.equals(other.playerName))
            return false;
        if (this.playerUuid == null) {
            if (other.playerUuid != null)
                return false;
        }
        else if (!this.playerUuid.equals(other.playerUuid))
            return false;
        if (this.prio == null) {
            if (other.prio != null)
                return false;
        }
        else if (!this.prio.equals(other.prio))
            return false;
        if (this.isBot == null) {
            if (other.isBot != null)
                return false;
        }
        else if (!this.isBot.equals(other.isBot))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.playerName == null) ? 0 : this.playerName.hashCode());
        result = prime * result + ((this.playerUuid == null) ? 0 : this.playerUuid.hashCode());
        result = prime * result + ((this.prio == null) ? 0 : this.prio.hashCode());
        result = prime * result + ((this.isBot == null) ? 0 : this.isBot.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TablistInfo (");

        sb.append(playerName);
        sb.append(", ").append(playerUuid);
        sb.append(", ").append(prio);
        sb.append(", ").append(isBot);

        sb.append(")");
        return sb.toString();
    }
}
