/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TablistText implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final OffsetDateTime time;
    private final String headerText;
    private final String headerJson;
    private final String footerText;
    private final String footerJson;

    public TablistText(TablistText value) {
        this.id = value.id;
        this.time = value.time;
        this.headerText = value.headerText;
        this.headerJson = value.headerJson;
        this.footerText = value.footerText;
        this.footerJson = value.footerJson;
    }

    public TablistText(
        Long id,
        OffsetDateTime time,
        String headerText,
        String headerJson,
        String footerText,
        String footerJson
    ) {
        this.id = id;
        this.time = time;
        this.headerText = headerText;
        this.headerJson = headerJson;
        this.footerText = footerText;
        this.footerJson = footerJson;
    }

    /**
     * Getter for <code>public.tablist_text.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.tablist_text.time</code>.
     */
    public OffsetDateTime getTime() {
        return this.time;
    }

    /**
     * Getter for <code>public.tablist_text.header_text</code>.
     */
    public String getHeaderText() {
        return this.headerText;
    }

    /**
     * Getter for <code>public.tablist_text.header_json</code>.
     */
    public String getHeaderJson() {
        return this.headerJson;
    }

    /**
     * Getter for <code>public.tablist_text.footer_text</code>.
     */
    public String getFooterText() {
        return this.footerText;
    }

    /**
     * Getter for <code>public.tablist_text.footer_json</code>.
     */
    public String getFooterJson() {
        return this.footerJson;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TablistText other = (TablistText) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.time == null) {
            if (other.time != null)
                return false;
        }
        else if (!this.time.equals(other.time))
            return false;
        if (this.headerText == null) {
            if (other.headerText != null)
                return false;
        }
        else if (!this.headerText.equals(other.headerText))
            return false;
        if (this.headerJson == null) {
            if (other.headerJson != null)
                return false;
        }
        else if (!this.headerJson.equals(other.headerJson))
            return false;
        if (this.footerText == null) {
            if (other.footerText != null)
                return false;
        }
        else if (!this.footerText.equals(other.footerText))
            return false;
        if (this.footerJson == null) {
            if (other.footerJson != null)
                return false;
        }
        else if (!this.footerJson.equals(other.footerJson))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.time == null) ? 0 : this.time.hashCode());
        result = prime * result + ((this.headerText == null) ? 0 : this.headerText.hashCode());
        result = prime * result + ((this.headerJson == null) ? 0 : this.headerJson.hashCode());
        result = prime * result + ((this.footerText == null) ? 0 : this.footerText.hashCode());
        result = prime * result + ((this.footerJson == null) ? 0 : this.footerJson.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TablistText (");

        sb.append(id);
        sb.append(", ").append(time);
        sb.append(", ").append(headerText);
        sb.append(", ").append(headerJson);
        sb.append(", ").append(footerText);
        sb.append(", ").append(footerJson);

        sb.append(")");
        return sb.toString();
    }
}
