/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TopKillsMonthView implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String killerPlayerName;
    private final UUID killerPlayerUuid;
    private final Long killCount;

    public TopKillsMonthView(TopKillsMonthView value) {
        this.killerPlayerName = value.killerPlayerName;
        this.killerPlayerUuid = value.killerPlayerUuid;
        this.killCount = value.killCount;
    }

    public TopKillsMonthView(
        String killerPlayerName,
        UUID killerPlayerUuid,
        Long killCount
    ) {
        this.killerPlayerName = killerPlayerName;
        this.killerPlayerUuid = killerPlayerUuid;
        this.killCount = killCount;
    }

    /**
     * Getter for <code>public.top_kills_month_view.killer_player_name</code>.
     */
    public String getKillerPlayerName() {
        return this.killerPlayerName;
    }

    /**
     * Getter for <code>public.top_kills_month_view.killer_player_uuid</code>.
     */
    public UUID getKillerPlayerUuid() {
        return this.killerPlayerUuid;
    }

    /**
     * Getter for <code>public.top_kills_month_view.kill_count</code>.
     */
    public Long getKillCount() {
        return this.killCount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TopKillsMonthView other = (TopKillsMonthView) obj;
        if (this.killerPlayerName == null) {
            if (other.killerPlayerName != null)
                return false;
        }
        else if (!this.killerPlayerName.equals(other.killerPlayerName))
            return false;
        if (this.killerPlayerUuid == null) {
            if (other.killerPlayerUuid != null)
                return false;
        }
        else if (!this.killerPlayerUuid.equals(other.killerPlayerUuid))
            return false;
        if (this.killCount == null) {
            if (other.killCount != null)
                return false;
        }
        else if (!this.killCount.equals(other.killCount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.killerPlayerName == null) ? 0 : this.killerPlayerName.hashCode());
        result = prime * result + ((this.killerPlayerUuid == null) ? 0 : this.killerPlayerUuid.hashCode());
        result = prime * result + ((this.killCount == null) ? 0 : this.killCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TopKillsMonthView (");

        sb.append(killerPlayerName);
        sb.append(", ").append(killerPlayerUuid);
        sb.append(", ").append(killCount);

        sb.append(")");
        return sb.toString();
    }
}
