/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TopPlaytimeAllTimeView implements Serializable {

    private static final long serialVersionUID = 1L;

    private final UUID playerUuid;
    private final String playerName;
    private final Long playtimeSeconds;

    public TopPlaytimeAllTimeView(TopPlaytimeAllTimeView value) {
        this.playerUuid = value.playerUuid;
        this.playerName = value.playerName;
        this.playtimeSeconds = value.playtimeSeconds;
    }

    public TopPlaytimeAllTimeView(
        UUID playerUuid,
        String playerName,
        Long playtimeSeconds
    ) {
        this.playerUuid = playerUuid;
        this.playerName = playerName;
        this.playtimeSeconds = playtimeSeconds;
    }

    /**
     * Getter for <code>public.top_playtime_all_time_view.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return this.playerUuid;
    }

    /**
     * Getter for <code>public.top_playtime_all_time_view.player_name</code>.
     */
    public String getPlayerName() {
        return this.playerName;
    }

    /**
     * Getter for
     * <code>public.top_playtime_all_time_view.playtime_seconds</code>.
     */
    public Long getPlaytimeSeconds() {
        return this.playtimeSeconds;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TopPlaytimeAllTimeView other = (TopPlaytimeAllTimeView) obj;
        if (this.playerUuid == null) {
            if (other.playerUuid != null)
                return false;
        }
        else if (!this.playerUuid.equals(other.playerUuid))
            return false;
        if (this.playerName == null) {
            if (other.playerName != null)
                return false;
        }
        else if (!this.playerName.equals(other.playerName))
            return false;
        if (this.playtimeSeconds == null) {
            if (other.playtimeSeconds != null)
                return false;
        }
        else if (!this.playtimeSeconds.equals(other.playtimeSeconds))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.playerUuid == null) ? 0 : this.playerUuid.hashCode());
        result = prime * result + ((this.playerName == null) ? 0 : this.playerName.hashCode());
        result = prime * result + ((this.playtimeSeconds == null) ? 0 : this.playtimeSeconds.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TopPlaytimeAllTimeView (");

        sb.append(playerUuid);
        sb.append(", ").append(playerName);
        sb.append(", ").append(playtimeSeconds);

        sb.append(")");
        return sb.toString();
    }
}
