/*
 * This file is generated by jOOQ.
 */
package vc.data.dto.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Worldtime implements Serializable {

    private static final long serialVersionUID = 1L;

    private final OffsetDateTime time;
    private final Long worldage;
    private final Long worldtime;

    public Worldtime(Worldtime value) {
        this.time = value.time;
        this.worldage = value.worldage;
        this.worldtime = value.worldtime;
    }

    public Worldtime(
        OffsetDateTime time,
        Long worldage,
        Long worldtime
    ) {
        this.time = time;
        this.worldage = worldage;
        this.worldtime = worldtime;
    }

    /**
     * Getter for <code>public.worldtime.time</code>.
     */
    public OffsetDateTime getTime() {
        return this.time;
    }

    /**
     * Getter for <code>public.worldtime.worldage</code>.
     */
    public Long getWorldage() {
        return this.worldage;
    }

    /**
     * Getter for <code>public.worldtime.worldtime</code>.
     */
    public Long getWorldtime() {
        return this.worldtime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Worldtime other = (Worldtime) obj;
        if (this.time == null) {
            if (other.time != null)
                return false;
        }
        else if (!this.time.equals(other.time))
            return false;
        if (this.worldage == null) {
            if (other.worldage != null)
                return false;
        }
        else if (!this.worldage.equals(other.worldage))
            return false;
        if (this.worldtime == null) {
            if (other.worldtime != null)
                return false;
        }
        else if (!this.worldtime.equals(other.worldtime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.time == null) ? 0 : this.time.hashCode());
        result = prime * result + ((this.worldage == null) ? 0 : this.worldage.hashCode());
        result = prime * result + ((this.worldtime == null) ? 0 : this.worldtime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Worldtime (");

        sb.append(time);
        sb.append(", ").append(worldage);
        sb.append(", ").append(worldtime);

        sb.append(")");
        return sb.toString();
    }
}
