name: 2b2t.vc-api Build

on:
  pull_request:
  push:
    branches:
      - "mainline"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - name: Elevate wrapper permissions
        run: chmod +x ./mvnw

      - name: Build 2b2t.vc-api
        run: ./mvnw install spring-boot:repackage

      - name: Upload Java Artifact
        uses: actions/upload-artifact@v7
        with:
          name: 2b2t.vc-api
          path: target/2b2t.vc-api-*.jar
          if-no-files-found: error
          archive: false
