name: 2b-api Build

on:
  pull_request:
  push:
    branches:
      - "mainline"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Elevate wrapper permissions
        run: chmod +x ./mvnw

      - name: Build ZenithProxy
        run: ./mvnw install
