name: 2b2t.vc-api PR Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'zulu'

      - name: Elevate wrapper permissions
        run: chmod +x ./mvnw

      - name: Build 2b2t.vc-api
        run: ./mvnw install
